### ISSUE TITLE
DDR_MEM_BW

### ISSUE THREAD

**Issue by chengscott** [meta-pytorch/torchrec#1005]
Hi,

I would like to know the assumption of DDR memory bandwidth [here](https://github.com/pytorch/torchrec/blob/main/torchrec/distributed/planner/constants.py#L24). The GPU seems like V100 32GB, but the system DDR memory bandwidth is so low, which is 1-channel 3200MT/s DDR4 only.

Thanks,
Scott

**Comment by YLGH** [comment]
Hey Scott - these values are pretty hard coded to some of meta's topology properties. Thanks for the diff to allow more flexibility - I'll have someone take a look at that

**Comment by YLGH** [comment]
PR medged
