### ISSUE TITLE
How does DistributedModelParallel work?

### ISSUE THREAD

**Issue by amogkam** [meta-pytorch/torchrec#102]
First off, this is an amazing library! Lots of very cool features, but I'm very curious about `DistributedModelParallel`.

What exactly does it do/how does it work? I couldn't really find much information in the docstrings/docs. How does it work with data parallel?

**Comment by colin2328** [comment]
Thanks @amogkam :)

DistributedModelParallel wraps your model and will shard the sparse (shardableModules) across available devices (GPUs)

See https://colab.research.google.com/github/pytorch/torchrec/blob/main/Torchrec_Introduction.ipynb for an intro, including this API

**Comment by amogkam** [comment]
Thanks @colin2328- I took a look at the tutorial and I have some follow up questions

1. What is considered a shardableModule? Is this only the embedding layers or is there model parallelism for the feed forward network as well?
2. Does the model parallelism work across multiple nodes?
3. When model parallelism is used with data parallelism is it just that each model replica in the data parallel group is also sharded across devices?

Let me know if any of my understanding is completely off!

**Comment by colin2328** [comment]
1) A shardableModule is a nn.module with a corresponding ShardedModule (https://pytorch.org/torchrec/torchrec.distributed.html#torchrec.distributed.types.ShardedModule)  - e.g ShardedEmbeddingBagCollection. The shardable module is sharded into the ShardedModule (i.e, can be sharded across devices).
Currently, torchrec only provides examples of sharding for embedding layers, but we are exploring dense layers as well

2) yes, see the dlrm example. TableWiseColumnWise sharding is this sharding scheme (where we shard table wise within a node and column wise across devices)

3) yes - by default, torchrec will shard (model parallel) sparse parts (embedding layers) across devices, then replicate dense parts across devices (using DDP). 
 going to close for now, but feel free to ask more qs
