### ISSUE TITLE
convert Criteo Terabyte Datasets sparse features into KeyedTensor or KeyedJaggedTensor

### ISSUE THREAD

**Issue by Hollen0318** [meta-pytorch/torchrec#1044]
Hi I am not familiar with the KeyedTensor or KeyedJaggedTensor, I want to transform my sparse input with shape of:

batch size * embedding dimensions:

For example, the first row of my sparse input looks like:

[971053,  32204,   8739,   8933,   6533,      8,   4381,   1737,     13, 915973, 470211, 279131,     27,    224,  24248,    183,      7,    960, 28, 878585, 689661, 402690, 321651,   1995,    120,     17]

The number indicates the embedding values, with each column's number of embeddings being:

[1000000, 50000, 25000, 10000, 25000, 10, 10000, 2500, 250, 1000000, 1000000, 500000, 100, 5000, 25000, 250, 10, 1500, 50, 1000000, 1000000, 1000000, 500000, 25000, 500, 50]

The embedding dimensions are same equals to 16.

How do I transform this sparse input into KeyedTensor so both inter_arch and sparse_arch can accept it?

So far I have tried using:

KeyedJaggedTensor.from_offset_sync, 

KeyedTensor.from_tensor_list.

Appreciate any tips!

**Comment by samiwilf** [comment]
@Hollen0318. See the following links:

#### How to create embedding tables:
Example 1: [pytorch.org/tutorials/intermediate/torchrec_tutorial.html#from-embeddingbag-to-embeddingbagcollection](https://pytorch.org/tutorials/intermediate/torchrec_tutorial.html#from-embeddingbag-to-embeddingbagcollection)
Example 2: [github.com/facebookresearch/dlrm/blob/main/torchrec_dlrm/dlrm_main.py#L587-L597](https://github.com/facebookresearch/dlrm/blob/main/torchrec_dlrm/dlrm_main.py#L587-L597)

#### How to create the KeyedJaggedTensor object (which stores the sparse inputs):
Example 1: [pytorch.org/tutorials/intermediate/torchrec_tutorial.html#representing-minibatches-with-keyedjaggedtensor](https://pytorch.org/tutorials/intermediate/torchrec_tutorial.html#representing-minibatches-with-keyedjaggedtensor)
Example 2: [github.com/facebookresearch/dlrm/blob/main/torchrec_dlrm/data/multi_hot_criteo.py#L206-L231](https://github.com/facebookresearch/dlrm/blob/main/torchrec_dlrm/data/multi_hot_criteo.py#L206-L231)
