### ISSUE TITLE
could we use torchrec binding all feature in cpp with libtorch  ?

### ISSUE THREAD

**Issue by mullerhai** [meta-pytorch/torchrec#1046]
Now ,we use libtorch for develop,we want to use torchrec in cpp,but not know if the feature  and function is same with python

**Comment by s4ayub** [comment]
Sorry a bit confused, torchrec is a python library, which aspects do you want to use in CPP?

**Comment by YLGH** [comment]
I think the answer to this question is no -  we only support the python APIs
