### ISSUE TITLE
does it support serving ?

### ISSUE THREAD

**Issue by ucas010** [meta-pytorch/torchrec#1105]
hi,dear
could it support torch serving? or any docs can be inference ?

**Comment by s4ayub** [comment]
Hi!

Do you mean TorchServe? ie. https://pytorch.org/serve/

We also have quantized modules in the quant folder, tests here: https://github.com/pytorch/torchrec/blob/main/torchrec/quant/tests/test_embedding_modules.py

**Comment by YLGH** [comment]
Also check out
https://github.com/pytorch/torchrec/tree/main/torchrec/inference

The example only shows single gpu serving for now
