### ISSUE TITLE
Does it support cuda11.8 and H100?

### ISSUE THREAD

**Issue by xyyintel** [meta-pytorch/torchrec#1108]
Does it support cuda11.8 and H100? If does, then what is the fgemm_gpu version and torch version they use?

**Comment by bigning** [comment]
Please check this https://fburl.com/u8rap45h

**Comment by YLGH** [comment]
@xyyintel I think this should be supported. Pytorch and fbgemm_gpu both work on it. We don't have any H100s to test on right now, but pls lmk if you're able to do so.
