### ISSUE TITLE
There is a mistake in Example of "class DLRM(nn.Module)" ? 

### ISSUE THREAD

**Issue by peitao** [meta-pytorch/torchrec#1120]
dense_arch_layer_sizes=[20],   But eb1_config and eb2_config 's embedding_dim == D 
Code:https://github.com/pytorch/torchrec/blob/2813bcd484bdde5c3081f9690fb0b0e7401f6ddd/torchrec/models/dlrm.py#L486

the example commet will 'raise ValueError(' 
https://github.com/pytorch/torchrec/blob/2813bcd484bdde5c3081f9690fb0b0e7401f6ddd/torchrec/models/dlrm.py#L530

I try it in colab
![image](https://user-images.githubusercontent.com/3378117/232053294-0877ec74-4b97-4930-9636-4cacdfa49d4e.png)
https://github.com/peitao/search-as-you-type/blob/master/test.ipynb

another mistake is "f2 is not pass to the model" in L503
https://github.com/pytorch/torchrec/blob/2813bcd484bdde5c3081f9690fb0b0e7401f6ddd/torchrec/models/dlrm.py#L503

**Comment by YLGH** [comment]
Hi,

Thanks for the catch - we'll make the fix in the notebook

**Comment by YLGH** [comment]
Made the fix to the docstrings in 

https://github.com/pytorch/torchrec/pull/1136
