### ISSUE TITLE
DeepFM and DLRM examples broken

### ISSUE THREAD

**Issue by VictorJouault** [meta-pytorch/torchrec#1132]
Both DLRM and DeepFM examples seem broken at multiple levels (argument errors, matrix multiplication doesn't work, features aren't present, ...). It would be great to fix that asap since it's really hard to get started using the models without concrete examples on how to use them.

Example: Ran `pip install torchrec` followed by the example code snippet for DLRM and DeepFM here: https://pytorch.org/torchrec/torchrec.models.html#

**Comment by YLGH** [comment]
Hey @VictorJouault, thanks for raising - 

I updated the docstrings and added some unit tests over the examples in https://github.com/pytorch/torchrec/pull/1136.

It may take a couple hours for the docs to be updated. Pls have a look at the new docstrings, and hopefully unblocks you. Closing issue for now, but feel free to reopen

**Comment by YLGH** [comment]
@VictorJouault  Also please check out 

https://github.com/pytorch/torchrec/tree/main/examples/golden_training

for the easiest example to get onboarded.
