### ISSUE TITLE
Initialize the parameters of EmbeddingCollection

### ISSUE THREAD

**Issue by DeepakSaini119** [meta-pytorch/torchrec#1165]
I want to initialize the embedding tables of an EmbeddingCollection. I try to do it like this:
```python
import os
import argparse
import numpy as np
import torch
import torch.multiprocessing as mp
import torch.distributed as dist
import torchrec
from torchrec.modules.embedding_configs import DataType


def setup(rank, args):
    torch.cuda.set_device(rank)

    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'

    dist.init_process_group("nccl", rank=rank, world_size=args.world_size)

    return None


def train(rank, embedding_tables, args):
    print(f"setting up in {rank}")
    setup(rank, args)

    model = torchrec.distributed.DistributedModelParallel(embedding_tables, device=torch.device(rank))

    if(rank == 0):
        print(model)
        print(model.plan)
        print("named params")
        for name, param in model.named_parameters():
            print(name, param.shape, param)

    label_index = torch.LongTensor([0,1,2]).to(rank)

    minibatch_kjt = torchrec.KeyedJaggedTensor(keys=["free_parameters"],
                                          values=label_index,
                                          lengths=torch.ones(len(label_index), dtype=torch.int64).to(label_index.device))
    free_params = model(minibatch_kjt)["free_parameters"].values()

    print("free_params:", free_params.shape, free_params)  # this should be [[0, 0, 0, ...], [1, 1, 1, ...], [2, 2, 2, ...]], but are random vectors still


if(__name__ == "__main__"):
    parser = argparse.ArgumentParser()
    args = parser.parse_args()

    args.nodes = 1
    args.gpus = torch.cuda.device_count()
    args.world_size = args.gpus * args.nodes

    
    embedding_tables = torchrec.EmbeddingCollection(device="cpu",  # I assume it actually allocates the embedding table on CPU 
                                               tables=[
                                                   torchrec.EmbeddingConfig(
                                                       name="free_parameters",
                                                       embedding_dim=64,
                                                       num_embeddings=10,
                                                       data_type=DataType.FP32
                                                       )
                                                   ]
                                               )
    

    lbl_embs = np.array([np.ones((64, ), dtype=np.float32) * i for i in range(10)])
    print(lbl_embs)  # is [[0, 0, 0, ...], [1, 1, 1, ...], [2, 2, 2, ...], ..., [9, 9, 9, ...]]
    
    with torch.no_grad():
        for name, param in embedding_tables.named_parameters():
            if name == 'embeddings.free_parameters.weight':
                print("Intializing table...")
                param.copy_(torch.tensor(lbl_embs))

    print(">>> Spawning processes")
    mp.spawn(train, nprocs=args.gpus, args=(embedding_tables, args,))
```

However, the EmbeddingCollection params are not being initialized as expected. Am I missing something here? Is there some other standard way to do this? TIA.

**Comment by YLGH** [comment]
my guess for what is happening is you are indeed initializing the parameters of the **unsharded model**, however, when you call DMP in def train, we swap out your EmbeddingCollection with a new module - i'm guessing this information isn't propagated down.

I'd recommend trying to do the initializing after you call Distributed Model Parallel

**Comment by DeepakSaini119** [comment]
Thanks @YLGH, I would prefer to initialize before the sharding actually happens because in case I try to initialize after sharding, I will have to either handle different cases depending on the sharding plan or have a fixed sharding plan in place. Is there a way to propagate the params of the unsharded model after the DMP call?

**Comment by DeepakSaini119** [comment]
Also, trying to initialize the params like this
```python
@torch.no_grad()
def init_weights(m):
    for param in m.parameters():
        torch.nn.init.ones_(param)
...
model = DistributedModelParallel(embedding_tables, device=torch.device(rank))
model.apply(init_weights)
```
doesn't seem to work either.

**Comment by YLGH** [comment]
@DeepakSaini119 
makes sense, I think this case we haven't handled too well because we usually have the unsharded table on meta device. I'll add it to the back log.

what was the error you had with the .apply(init_weights)?

**Comment by DeepakSaini119** [comment]
There is no error with ` .apply(init_weights)`. Just that the params don't get initialized as expected.

**Comment by YLGH** [comment]
> There is no error with ` .apply(init_weights)`. Just that the params don't get initialized as expected.

I see - thanks for report, we'll look into it cc @zainhuda

**Comment by zainhuda** [comment]
Hey @DeepakSaini119, working on implementing the functionality for you. I will update you when it's landed (very soon!)

**Comment by DeepakSaini119** [comment]
Thanks @zainhuda, and also thanks to the entire team for open sourcing the wonderful library

**Comment by zainhuda** [comment]
Hey @DeepakSaini119 just wanted to keep you in the loop, on the home stretch for the unit tests on this change. Should be landed ASAP, thanks for your patience!

**Comment by zainhuda** [comment]
@DeepakSaini119 changes are landing now, should be merged soon and you should be able to use it in the pattern you described earlier. Thanks for your patience!

**Comment by zainhuda** [comment]
@DeepakSaini119 this usage pattern for EmbeddingBagCollection should be landed soon as well if needed for your use.

**Comment by DeepakSaini119** [comment]
Hey @zainhuda, thanks for the changes. However, I am not able to get fbgemm-gpu to work even after much effort. Do you have a combination of CUDA, python, torch, fbgemm-gpu versions that seem to work. Currently I am trying to install nightly versions of torch, fbgemm-gpu but somehow I am missing some things.

**Comment by DeepakSaini119** [comment]
@zainhuda, when trying to use your commit, I get the error described in https://github.com/pytorch/FBGEMM/issues/1847. I can see that the embedding table is initialized correctly, however, the actual retrieval step(`model(minibatch_kjt)["free_parameters"].values()`) fails. Do you have any idea what might be going wrong here by any chance?
