### ISSUE TITLE
[INT8] Shard tensor size does not match with metadata.shard_lengths

### ISSUE THREAD

**Issue by unavailableun** [meta-pytorch/torchrec#1180]
Hi, 

I am trying to train INT8 datatype embeddings, while hitting below exception:
 ```
  File "/home/local_git_sources/deeprank/lightning/src/smile_lightning/apps/hybrid_nn/common/modules/sharded_multi_task.py", line 88, in __init__
    self.dist_model = DistributedModelParallel(
  File "/opt/lib/python3.8/site-packages/torchrec/distributed/model_parallel.py", line 225, in __init__
    self._dmp_wrapped_module: nn.Module = self._init_dmp(module)
  File "/opt/lib/python3.8/site-packages/torchrec/distributed/model_parallel.py", line 283, in _init_dmp
    return self._shard_modules_impl(module)
  File "/opt/lib/python3.8/site-packages/torchrec/distributed/model_parallel.py", line 330, in _shard_modules_impl
    child = self._shard_modules_impl(
  File "/opt/lib/python3.8/site-packages/torchrec/distributed/model_parallel.py", line 330, in _shard_modules_impl
    child = self._shard_modules_impl(
  File "/opt/lib/python3.8/site-packages/torchrec/distributed/model_parallel.py", line 330, in _shard_modules_impl
    child = self._shard_modules_impl(
  [Previous line repeated 2 more times]
  File "/opt/lib/python3.8/site-packages/torchrec/distributed/model_parallel.py", line 321, in _shard_modules_impl
    module = self._sharder_map[sharder_key].shard(
  File "/opt/lib/python3.8/site-packages/torchrec/distributed/embeddingbag.py", line 570, in shard
    return ShardedEmbeddingBagCollection(
  File "/opt/lib/python3.8/site-packages/torchrec/distributed/embeddingbag.py", line 332, in __init__
    self._create_lookups()
  File "/opt/lib/python3.8/site-packages/torchrec/distributed/embeddingbag.py", line 394, in _create_lookups
    self._lookups.append(sharding.create_lookup())
  File "/opt/lib/python3.8/site-packages/torchrec/distributed/sharding/tw_sharding.py", line 397, in create_lookup
    return GroupedPooledEmbeddingsLookup(
  File "/opt/lib/python3.8/site-packages/torchrec/distributed/embedding_lookup.py", line 232, in __init__
    self._emb_modules.append(_create_lookup(config, device))
  File "/opt/lib/python3.8/site-packages/torchrec/distributed/embedding_lookup.py", line 219, in _create_lookup
    return BatchedFusedEmbeddingBag(
  File "/opt/lib/python3.8/site-packages/torchrec/distributed/batched_embedding_kernel.py", line 623, in __init__
    self._optim: EmbeddingFusedOptimizer = EmbeddingFusedOptimizer(
  File "/opt/lib/python3.8/site-packages/torchrec/distributed/batched_embedding_kernel.py", line 168, in __init__
    local_weight_shards.append(Shard(local_weight, local_metadata))
  File "<string>", line 5, in __init__
  File "/opt/lib/python3.8/site-packages/torch/distributed/_shard/sharded_tensor/shard.py", line 27, in __post_init__
    raise ValueError(
ValueError: Shard tensor size does not match with metadata.shard_lengths! Found shard tensor size: [1000, 20], metadata.shard_lengths: [1000, 12], 
```

I found that dim was added by 8 here:
```Python
INT8_EMB_ROW_DIM_OFFSET = 8
```
![image](https://github.com/pytorch/torchrec/assets/98440317/ec5aec91-73be-46db-a927-c31e6fea7c9b)

Why add 8 here? How can I resolve the mismatch issue?

Thanks!

**Comment by henrylhtsang** [comment]
Hi,

So this problem has many layers.

1. Why do we add 8 for int8 quantization?
When we do int8 quantization, we need to store two more fp32 for range. Hence adding dim 8 gives us 64 bits to do that.

2. Why do we add 8 here?
Because we use fbgemm kernel, which would also add 8 to the tensor size, see https://github.com/pytorch/FBGEMM/blob/main/fbgemm_gpu/fbgemm_gpu/split_table_batched_embeddings_ops_training.py#L1183

3. Does line 383 cause the error?
No! Because _gen_named_parameters_by_table_fused is called after EmbeddingFusedOptimizer. In fact, the error didn't happen because we added 8. It happened because we _didn't_ add 8. If we look at the error message again, it says that the tensor (coming from the fbgemm kernel, which has added 8) has dim 20, while the local metadata (coming from config) has dim 12. 

Solution(?):
I guess you can try updating local_metadata manually in this case. But it's hard to tell if this is just a bug, i.e., we forgot to also update local_metadata, or if the feature isn't ready yet. I think the optimizer might not be set up to support quantitized embedding tables with elementwise optimizers. In the long run, we can revisit it, but we are more interesting in the inference side of int8 quantization.

EDIT:
Also, can you let me know how to reproduce this error?

**Comment by unavailableun** [comment]
@henrylhtsang Thanks for your response. 
1. Can you point me where to update ``local_metadata``?
2. I just set data_type as INT8 as below, then triggered the exception.
```Python
                config = EmbeddingBagConfig(
                    .......
                    data_type=DataType.INT8,
                )
```

**Comment by henrylhtsang** [comment]
@unavailableun 

So I tried to see how far I can reproduce and fix the problem. The tldr is I think the feature is not ready yet. Here is what I tried.

I added the DataType to test_sharding_ebc_as_top_level under test_model_parallel_base.py. Then I ran test_model_parallel_gloo. After fixing a cache_precision issue, I was able to reproduce the error.

Then I added 8 to the local_metadata under batched_embedding_kernel.py.
```
for local_weight, local_metadata in zip(
    shard_params.embedding_weights, shard_params.local_metadata
):
    local_metadata.shard_sizes[1] = local_metadata.shard_sizes[1] + 8 # add this line
    local_weight_shards.append(Shard(local_weight, local_metadata))
```

This gives an assertion error in init_parameters under BaseBatchedEmbeddingBag. I tried hacking it by 
```
assert param.shape == (rows, emb_dim + 8)  # pyre-ignore[16]
```
but then got another error 
>     1) RuntimeError: "check_uniform_bounds" not implemented for 'Byte'
>       File "/usr/local/fbcode/platform010/lib/python3.8/contextlib.py", line 120, in __exit__
>         next(self.gen)
>       File "/usr/local/fbcode/platform010/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
>         yield
>       File "/usr/local/fbcode/platform010/lib/python3.8/unittest/case.py", line 676, in run
>         self._callTestMethod(testMethod)
>       File "/usr/local/fbcode/platform010/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
>         method()
>       File "torchrec/distributed/test_utils/test_model_parallel_base.py", line 219, in test_sharding_ebc_as_top_level
>         model = DistributedModelParallel(ebc, device=curr_device)
>       File "torchrec/distributed/model_parallel.py", line 236, in __init__
>         self._dmp_wrapped_module: nn.Module = self._init_dmp(module)
>       File "torchrec/distributed/model_parallel.py", line 301, in _init_dmp
>         return self._shard_modules_impl(module)
>       File "torchrec/distributed/model_parallel.py", line 339, in _shard_modules_impl
>         module = self._sharder_map[sharder_key].shard(
>       File "torchrec/distributed/embeddingbag.py", line 695, in shard
>         return ShardedEmbeddingBagCollection(
>       File "torchrec/distributed/embeddingbag.py", line 398, in __init__
>         self._create_lookups()
>       File "torchrec/distributed/embeddingbag.py", line 600, in _create_lookups
>         self._lookups.append(sharding.create_lookup())
>       File "torchrec/distributed/sharding/tw_sharding.py", line 332, in create_lookup
>         return GroupedPooledEmbeddingsLookup(
>       File "torchrec/distributed/embedding_lookup.py", line 309, in __init__
>         self._emb_modules.append(_create_lookup(config, device))
>       File "torchrec/distributed/embedding_lookup.py", line 296, in _create_lookup
>         return BatchedFusedEmbeddingBag(
>       File "torchrec/distributed/batched_embedding_kernel.py", line 887, in __init__
>         self.init_parameters()
>       File "torchrec/distributed/batched_embedding_kernel.py", line 752, in init_parameters
>         param.data.uniform_(  # pyre-ignore[16]

So I think I will leave it at that.
