### ISSUE TITLE
AttributeError: module 'torchrec' has no attribute 'models'

### ISSUE THREAD

**Issue by santoshcoder23** [meta-pytorch/torchrec#1195]
installed the cpu version of torchrec as mention in readme file on google colab.

B = 20
D = 3
in_features = 10
dense_arch = **torchrec.models.deepfm.DenseArch**(in_features=10, hidden_layer_size=10, embedding_dim=D)
dense_embedded = dense_arch(torch.rand((B, 10)))

**AttributeError**                            Traceback (most recent call last)
[<ipython-input-7-29ce3ae9c0f5>](https://localhost:8080/#) in <cell line: 4>()
      2 D = 3
      3 in_features = 10
----> 4 dense_arch = torchrec.models.deepfm.DenseArch(in_features=10, hidden_layer_size=10, embedding_dim=D)
      5 dense_embedded = dense_arch(torch.rand((B, 10)))

AttributeError: module 'torchrec' has no attribute 'models'

`

**Comment by henrylhtsang** [comment]
Hi,

Can you try adding `import torchrec.models` as well?

**Comment by santoshcoder23** [comment]
Thanks @henrylhtsang . It worked :)
