### ISSUE TITLE
Example for apply torchrec to train DLRM with custom input data

### ISSUE THREAD

**Issue by king0980692** [meta-pytorch/torchrec#1196]
Hi,

I'm new to torchrec repo, I have read the DLRM repo and its paper, but I found its implementation only for benchmarking the performance of Criteo dataset.

I notice that in torchrec repo have more organized code with DLRM model, so I am curious how can I train custom dataset (different size of dense feature and sparse feature) with torchrec ?

**Comment by henrylhtsang** [comment]
Hi,

I think you just need to make your own dataloader (i.e., `train_dataloader = get_dataloader(args, backend, "train")`) and setup `eb_configs` correctly (i.e., provide your own `DEFAULT_CAT_NAMES` and `DEFAULT_INT_NAMES`).
