### ISSUE TITLE
getting error in dlrm example

### ISSUE THREAD

**Issue by santoshcoder23** [meta-pytorch/torchrec#1212]
trying to implement dlrm example as in [https://pytorch.org/torchrec/torchrec.models.html](https://pytorch.org/torchrec/torchrec.models.html)
`import torch
import torchrec

import torchrec.models 
import torchrec.modules
import  torchrec.sparse

#torchrec.modules.embedding_configs.EmbeddingBagConfig
#torchrec.modules.embedding_modules.EmbeddingBagCollection
#torchrec.models.dlrm.DLRM
B = 2
D = 8

eb1_config = torchrec.modules.embedding_configs.EmbeddingBagConfig(
   name="t1", embedding_dim=D, num_embeddings=100, feature_names=["f1", "f3"]
)
eb2_config = torchrec.modules.embedding_configs.EmbeddingBagConfig(
   name="t2",
   embedding_dim=D,
   num_embeddings=100,
   feature_names=["f2"],
)

ebc = torchrec.modules.embedding_modules.EmbeddingBagCollection(tables=[eb1_config, eb2_config])
model = torchrec.models.dlrm.DLRM(
   embedding_bag_collection=ebc,
   dense_in_features=100,
   dense_arch_layer_sizes=[20],
   over_arch_layer_sizes=[5, 1],
)`

Error:  _ValueError: embedding_bag_collection dimension (8) and final dense arch layer size ({dense_arch_layer_sizes[-1]}) must match_. at  model = torchrec.models.dlrm.DLRM(

**Comment by henrylhtsang** [comment]
Hi,

I think the example has a typo. Just change
`dense_arch_layer_sizes=[20],`
to 
`dense_arch_layer_sizes=[20, 8],`

Same issue as https://github.com/pytorch/torchrec/issues/1120
