### ISSUE TITLE
How to save sharded embedding as torch.nn.Embedding

### ISSUE THREAD

**Issue by Ye-Tian-Zero** [meta-pytorch/torchrec#1220]
I want to use sharded embedding in training for speeding up and reducing GPU memory usage. But after training, I want to save it as a traditional torch.nn.Embedding for serving (which is not distributed). I guess I can fetch all the indices in the sharded embedding and then init a torch.nn.embedding with them and then save it, but maybe there are some other more elegant ways?

**Comment by henrylhtsang** [comment]
I think you can take a look at torchsnapshot, see the example [here](https://github.com/pytorch/torchsnapshot/blob/087caae16ac83c99783fdb698fa1e3804a2a1670/examples/torchrec/main.py#L27). Though I am not sure how well maintained it is.

Another way is to iterate through state_dict and call ShardedTensor.gather to rank 0, but that may result in OOM if not done carefully.
