### ISSUE TITLE
row wise parallelism on CPUs

### ISSUE THREAD

**Issue by xiexbing** [meta-pytorch/torchrec#1252]
I am training DLRM built on torchrec v0.3.2 with CPUs, and I want to use row wise parallelism on some sparse embedding tables. the yaml configurations and the Warning message are shown as below:

 _target_: work.core.nn.SparseFeatureConfig
    embedding_dim: 64
    hash_size: 180000000
    sharding_constraints:
      _target_: torchrec.distributed.planner.ParameterConstraints
    sharding_types:
       - row_wise
      index: 1

[torchrec.distributed.planner.enumerators][WARNING] - No available sharding types after applying user provided constraints for t_table1.

And it ends as no sharding type is assigned to t_table1, and the run failed. 

My question is: does torchrec support row_wise sharding on CPUs? Or there's any specific configurations I should follow?

**Comment by YLGH** [comment]
Hi @xiexbing, unfortunately rowwise sharding is not supported on CPUs :(, I'd recommend to try using column wise

**Comment by xiexbing** [comment]
I see. Can I ask the specific reason why not implement row wise sharding for CPUs?

**Comment by YLGH** [comment]
I think the GLOO collective call backend (used for CPU) doesn't support reduce scatter (needed for rw sharding) atm

**Comment by xiexbing** [comment]
I see. thanks!

**Comment by YLGH** [comment]
Closing issue for now, feel free to re-open.
