### ISSUE TITLE
the support of dynamic embedding 

### ISSUE THREAD

**Issue by xiexbing** [meta-pytorch/torchrec#1256]
Hello,

I came across a torchrec PR discussing a new function called dynamic embedding, which includes some functionality of asynchronous PS seen in the tensorflow recommenders. I am wondering is this function is currently included in torchrec, and how to use it.

**Comment by zainhuda** [comment]
Hey, it is included in torchrec under `contrib/dynamic_embedding` (https://github.com/pytorch/torchrec/tree/main/contrib/dynamic_embedding). You can find the documentation under the README in that directory. Keep in mind you will have to separately install dynamic embeddings after you clone the torchrec repo.

**Comment by xiexbing** [comment]
got it, thanks. does it support cpu training?

**Comment by zainhuda** [comment]
not entirely sure for dynamic embeddings specifically, but you can train on cpu using TRec so it should apply for the dynamic embeddings as well
