### ISSUE TITLE
[WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by JamesMachine** [meta-pytorch/torchrec#1259]
Hi, I used pip install torchrec, which was successful. Yet, when I tried to import torchrec, this error showed up.

"[WinError 193] %1 is not a valid Win32 application"

This error only happened in my vscode. (My laptop is system type is: "64-bit operating system, x64-based processor" with Nvidia GeForce MX450) Running the tutorial code in colab was not a problem that everything ran smoothly.

Is there any problem? Any solutions? Any Suggestions?

**Comment by henrylhtsang** [comment]
Maybe related: https://github.com/pytorch/pytorch/issues/41585

Did you use conda? Is there a way to reproduce the error?
