### ISSUE TITLE
Avoid using `torch.empty` as the input to operations

### ISSUE THREAD

**Issue by kurtamohler** [meta-pytorch/torchrec#1268]
A PR of mine in pytorch (https://github.com/pytorch/pytorch/pull/101849) was reverted (https://github.com/pytorch/pytorch/pull/104302) because it broke a test in torchrec. I think we may have to coordinate a change in torchrec to reland it.

My PR changed `torch.empty` so that it fills the result with NaN if deterministic mode is turned on. This made the following assert in torchrec fail: https://github.com/pytorch/torchrec/blob/b3d3badc5ab4ce5ae861ca407749e32d2a002207/torchrec/distributed/composable/tests/test_fsdp.py#L229

The reason it fails is because the test is being run in deterministic mode and it's using the results of a `torch.empty` call as one of the inputs to a sum and then performing a comparison. A sum that contains a NaN always results in a NaN, and a comparison between any value and NaN always results in False.

When I changed the following `torch.empty` call in my local checkout of torchrec to `torch.randn`, the test passes: https://github.com/pytorch/torchrec/blob/f11b8ecc3a2f58929b3957494dccbd465267c7f2/torchrec/distributed/test_utils/test_model.py#L282

There may be other `torch.empty` calls in torchrec which could potentially be changed as well

**Comment by YLGH** [comment]
nice catch, thanks for the explanation. I'll put out a diff to change this to randn

**Comment by YLGH** [comment]
should be landed in https://github.com/pytorch/torchrec/pull/1269
