### ISSUE TITLE
How to initialize FusedEmbeddingBagCollection&DMP with Adam optimizer? 

### ISSUE THREAD

**Issue by newsbreak-tianxiang** [meta-pytorch/torchrec#1275]
I'm trying to use adam optimizer in cuda for a DMP model with FusedEmbeddingBagCollection. Following is a example code:

```
class demo(nn.Module):
    def __init__(self):
        super(demo, self).__init__()
        self.ebc = FusedEmbeddingBagCollection(
            tables=[torchrec.EmbeddingBagConfig(name="xx", embedding_dim=10, num_embeddings=32)]
            optimizer_type=torch.optim.Adam, optimizer_kwargs={"lr": .01},  
            device=torch.device('meta')
         )

```
When i'm trying to inilitialize the dmp model as following code
```
model = demo()
model = DistributedModelParallel(
            module=model,
            env=ShardingEnv.from_process_group(pg),
            plan=plan,
            device=device,
        )
``` 
I come up with the error: Adam optimizer is not supported in cpu. In my case, i need to initialize the model with 'meta' device  and then get the shard plan in dmp initialization.  As i known, the FusedEmbeddingBagCollection require the optimizer_type in definition, and my question is how to initialize the FusedEmbeddingBagCollection with adam optimizer for a dmp model ?

**Comment by YLGH** [comment]
hey @newsbreak-tianxiang, 

We actually recommend to use the apply_optim_in_backward API instead of directly using FusedEmbeddingBagCollection,

for an example pls see 

https://github.com/pytorch/torchrec/blob/main/torchrec/distributed/composable/tests/test_embeddingbag.py#L103

just replace SGD with Adam.

QQ - are you going to be running this over GLOO backend with cpu device? 

Unfortunantely the fused adam optimizer (as indicated by error message) is only supported on cuda (after you do the sharding).

**Comment by newsbreak-tianxiang** [comment]
Thanks for your resp. I still have some questions for this example:
1. At the implementation level, is the combination of `apply_optim_in_backward`+`EmbeddingBagCollection` equivalent to `FusedEmbeddingBagCollection`? From the code, i found that `FusedEmbeddingBagCollection` uses the fbgemm `SplitTableBatchedEmbeddingBagsCodegen`, while `EmbeddingBagCollection` is based on torch.nn.EmbeddingBag.
2. I'm not running over the gloo backend with cpu device, i'm just initilizing the model with `meta` FusedEmbeddingBagCollection, and i found the embeddingcollection will init with cpu if using the `meta` device.  In my code, i need to init the FusedEmbeddingBagCollection firstly in model definition and then convert it to a dmp model.

**Comment by YLGH** [comment]
> At the implementation level, is the combination of apply_optim_in_backward+EmbeddingBagCollection equivalent to FusedEmbeddingBagCollection? From the code, i found that FusedEmbeddingBagCollection uses the fbgemm SplitTableBatchedEmbeddingBagsCodegen, while EmbeddingBagCollection is based on torch.nn.EmbeddingBag.

For your use case it should be, once you pass apply_optim_in_backward + EBC, the torchrec sharder will swap this out with an equivalent SplitTableBatchedEmbeddingBagsCodegen (same as unsharded FusedEBC case), that matches your optimizer settings.
