### ISSUE TITLE
does does torchrec support hierarchical storage like hbm/mem/ssd?

### ISSUE THREAD

**Issue by zmxdream** [meta-pytorch/torchrec#1281]
does torchrec support hierarchical storage like hbm/mem/ssd?

**Comment by henrylhtsang** [comment]
Hi @zmxdream, Sorry for the late reply. Right now we only support hbm and ddr. See https://github.com/pytorch/torchrec/blob/03ab562c68b868da7885a57cec89bc688bd5a26a/torchrec/distributed/planner/types.py#L76

On the other hand, I think dynamic embeddings provides support for parameter server, so maybe that's something you can take a look.

**Comment by zmxdream** [comment]
thanks, i see
