### ISSUE TITLE
Nightly packages should have same package name as regular packages

### ISSUE THREAD

**Issue by ezyang** [meta-pytorch/torchrec#1313]
Currently torchrec distributes nightlies named as torchrec-nightly. This means you can have simultaneously have both torchrec and torchrec-nightly installed at the same time, which leads to obscure errors.

**Comment by colin2328** [comment]
cc @henrylhtsang  @osalpekar let's fix this, we can use nova release?

**Comment by osalpekar** [comment]
Will work with @henrylhtsang to get torchrec onto canonical Nova releases (like the rest of the domains)

**Comment by henrylhtsang** [comment]
Hi, with us onboarded to nova, now nightly and stable packages have the same name. See readme for more details.
