### ISSUE TITLE
How to process the Criteo Kaggle Ad/ Criteo Terabyte dataset in order to run the example?

### ISSUE THREAD

**Issue by Ash-Zheng** [meta-pytorch/torchrec#135]
I am trying to run the example with Criteo Kaggle Ad/ Criteo Terabyte dataset, It seems that the processed binary files are needed if I want to use the `InMemoryBinaryCriteoIterDataPipe` dataloader. 

I am wondering how to process the `.txt` file of Criteo Kaggle Ad/ Criteo Terabyte in order to run the example? Or could you provide the code for data process?

**Comment by samiwilf** [comment]
Hi Ash Zheng.  You'd use the script in https://github.com/pytorch/torchrec/blob/main/torchrec/datasets/scripts/npy_preproc_criteo.py.

**Comment by s4ayub** [comment]
You can run it like:

```
python datasets/scripts/npy_preproc_criteo.py --input_dir path_to_tsvs --output_dir directory_to_store_npy_files
```

**Comment by Ash-Zheng** [comment]
> Hi Ash Zheng. You'd use the script in https://github.com/pytorch/torchrec/blob/main/torchrec/datasets/scripts/npy_preproc_criteo.py.

Got it, thanks!
