### ISSUE TITLE
torchrec memory benchmark 

### ISSUE THREAD

**Issue by xiexbing** [meta-pytorch/torchrec#1413]
Hello, I am trying to repeat the memory benchmark experiments in this torchrec paper, https://arxiv.org/pdf/2104.05158.pdf
The paper suggests the benchmarks can be found from https://github.com/facebookresearch/param

but I cannot find the code for the memory benchmark (Figure 15 in the paper), embedding forward memory bandwidth. Can you please point me to the code? 

another thing is: in the experiment setting, it describes as:  Number of rows: 1000000, Number of tables: 64, Embedding dimension: 128, Pooling size: 32, rows per thread block: 32

how to set rows per thread block?

**Comment by henrylhtsang** [comment]
Hi, this doesn't seem related to torchrec. I would say either try finding it in https://github.com/facebookresearch/param, leave an issue there, or email the authors.
