### ISSUE TITLE
Make fbgemm an optional dependency

### ISSUE THREAD

**Issue by akreuzer** [meta-pytorch/torchrec#1483]
Installing `fbgemm` is complicated and sometimes not possible. For instance, `fbgemm` is not available for Mac M1, see https://github.com/pytorch/FBGEMM/issues/1985, or it does not work on Vertex AI out of the box, see https://github.com/pytorch/torchrec/issues/886.

Several parts of torechrec do not depend on `fbgemm`, for instance, `JaggedTensor`, everything under `torchrec.modules.*`, datasets, etc.
Thus, it would make those parts much easier to use if `fbgemm` would not be required for that.

From what I can see one could just move `fbgemm` to an extra dependency and only import `torchrec.quant` in [`torchrec/__init__.py`](https://github.com/pytorch/torchrec/blob/5fce39c3fcd187b472b65b15a46dd8e9aeb2c133/torchrec/__init__.py) if `fbgemm` is available.

**Comment by henrylhtsang** [comment]
@colin2328 what do you think? Sounds like something we can do?

**Comment by henrylhtsang** [comment]
After discussing with @colin2328, we won't be making fbgemm an optional. But feel free to hack it to use it on mac os.
