### ISSUE TITLE
[Bug] cpu_only fbgemm won't compile "permute_pooled_embs_auto_grad"

### ISSUE THREAD

**Issue by RabbitWhite1** [meta-pytorch/torchrec#160]
The used [fbgemm @ c3a26e1](https://github.com/pytorch/FBGEMM/tree/c3a26e17e7c514041ae3d08f39d0e19063614869) is buggy when compiling with "--cpu_only". 

As specified in [CMakeLists.txt](https://github.com/pytorch/FBGEMM/blob/c3a26e17e7c514041ae3d08f39d0e19063614869/fbgemm_gpu/CMakeLists.txt#L239), "src/permute_pooled_embedding_ops_gpu.cpp" will only compile when "NOT FBGEMM_CPU_ONLY", which means the method "permute_pooled_embs_auto_grad" won't be generated when "--cpu_only". However, this method is used by column_wise sharding.

To correctly support "--cpu_only", see the pr in [FBGEMM#987](https://github.com/pytorch/FBGEMM/pull/987)

**Comment by jianyuh** [comment]
Thanks @RabbitWhite1 for reporting this issue! We are working on fixing this issue with https://github.com/pytorch/FBGEMM/pull/950 as you mentioned. Currently the major blocker on landing the PR is due to some internal backward compatibility issues. Will push on landing it soon. cc @geyyer

**Comment by geyyer** [comment]
PR https://github.com/pytorch/FBGEMM/pull/987 fixing the issue was landed.

**Comment by colin2328** [comment]
Thanks @geyyer . Closing this issue. @RabbitWhite1  feel free to file another issue if needed
