### ISSUE TITLE
How to correctly run example/dlrm with cpu in multiple nodes?

### ISSUE THREAD

**Issue by RabbitWhite1** [meta-pytorch/torchrec#161]
Hi to all! I tried to run example/dlrm in multiple nodes after fixing `permute_pooled_embs_auto_grad` problem with #160 . But it was stuck at

torchrec.distributed.model_parallel.DistributedModelParallel.\_\_init\_\_ → 
init_data_parallel → 
self._data_parallel_wrapper.wrap (which is in DefaultDataParallelWrapper) → 
DistributedDataParallel.\_\_init\_\_ → 
dist._verify_params_across_proccesses

without any progress (cpus are waiting and no traffic in network).

**Could someone help me to see what causes this? Thanks in advance!** @liangluofb

My torchrec commit version is `b72ed51545d0682547e903f4a921f8d3082ef888`, and torch version is `1.12.0.dev20220312`. 
The torchrec and used fbgemm(see #160 ) are all built from source.

**How to reproduce?**
I used two nodes(node0 with IP as 10.0.0.1, and node1 with IP as 10.0.0.2). Then I run the below command:
```shell
#At node0
torchrun --nnodes 2 --nproc_per_node 1 --node_rank 0 --master_addr=10.0.0.1 --master_port=1234 dlrm_main.py --pin_memory --batch_size 8192 --epochs 1 --num_embeddings_per_feature "22760543,39060,17295,7424,20265,3,7122,1543,63,13022467,3067956,405282,10,2209,11938,155,4,976,14,29277564,40790948,18718810,590152,12973,108,36" --embedding_dim 128 --dense_arch_layer_sizes "512,256,128" --over_arch_layer_sizes "1024,1024,512,256,1" --learning_rate 5.0

#At node1
torchrun --nnodes 2 --nproc_per_node 1 --node_rank 1 --master_addr=10.0.0.1 --master_port=1234 dlrm_main.py --pin_memory --batch_size 8192 --epochs 1 --num_embeddings_per_feature "22760543,39060,17295,7424,20265,3,7122,1543,63,13022467,3067956,405282,10,2209,11938,155,4,976,14,29277564,40790948,18718810,590152,12973,108,36" --embedding_dim 128 --dense_arch_layer_sizes "512,256,128" --over_arch_layer_sizes "1024,1024,512,256,1" --learning_rate 5.0
```

**Comment by RabbitWhite1** [comment]
I later found that it seems only the current nightly torch (1.12.0.dev20220312) can reproduce this problem. When I switch to 1.11.0, it can run smoothly. But could anyone tell me why?

**Comment by dstaay-fb** [comment]
Ok great, at least you have it working!  Hard to know source of issue without a bit more debugging.

To clarify:
Using TorchRec Master + Nightly Pytorch Build -> unable to progress past "dist._verify_params_across_proccesses"
Using TorchRec Master + Pytorch Stable (1.11.0) -> working

To debug further, could you move to latest nightly builds, and:
1) confirm if issue persists,
2) if so, does it work when using only 1 node?

**Comment by RabbitWhite1** [comment]
Hi, thanks for your advice. I found that blocking is because of the version of my 2 nodes mismatch. And it looks good with the correct setup. Thus I will close this issue.
