### ISSUE TITLE
assert table.local_cols % 4 == 0

### ISSUE THREAD

**Issue by forcekeng** [meta-pytorch/torchrec#1612]
There's a `assert table.local_cols % 4 == 0` in `class BatchedFusedEmbeddingBag`, which in file `torchrec/torchrec/distributed
/batched_embedding_kernel.py`  with line number `852`. The assertion makes sure the embedding size is $4z, z={1,2,\cdots}$. I just want to know what happened in my experientment when embedding size is `1` or `2`, it doesn't work and throw this assertion error. It works when embedding size is `8` or `64` (tested). Is there anyway I can fix it?

```python
class BatchedFusedEmbeddingBag`(
 ...
            assert table.local_cols % 4 == 0, (
                f"table {table.name} has local_cols={table.local_cols} "
                "not divisible by 4. "
            )`
```

**Comment by gnahzg** [comment]
embedding size means rows. local_cols is the local column number after sharding. They are two different concepts.

**Comment by henrylhtsang** [comment]
We can't really fix it. There is an assertion to check the dim is divisible by 4 in FBGEMM (the kernel) to check that.

See also https://github.com/pytorch/torchrec/issues/1495
