### ISSUE TITLE
[Documentation] `EmbeddingBagCollectionConfig` is in the documentation, but it does not actually exist

### ISSUE THREAD

**Issue by sdhdez** [meta-pytorch/torchrec#193]
Hi,

Class `EmbeddingBagCollectionConfig` appears in some examples of the documentation, however it doesn't seem to be found in the code. 

https://pytorch.org/torchrec/torchrec.models.html#torchrec.models.deepfm.SimpleDeepFMNN
https://pytorch.org/torchrec/torchrec.models.html#torchrec.models.deepfm.SparseArch
https://pytorch.org/torchrec/torchrec.models.html#torchrec.models.dlrm.DLRM
https://pytorch.org/torchrec/torchrec.models.html#torchrec.models.dlrm.SparseArch

I've searched locally and it's only found in docstrings. 

![image](https://user-images.githubusercontent.com/2230157/161818108-23c090a8-e0bb-4eb4-9639-a06428bcdb3a.png)

**Comment by joshuadeng** [comment]
Hi @sdhdez, thanks for pointing that out! The documentation is incorrect, the EmbeddingBagCollection constructor will directly take in the tables, the list of EmbeddingTableConfigs. I think EmbeddingBagCollectionConfig might have been an argument from a legacy interface of EmbeddingBagCollection. 

I'll update the documentation to fix the error.
