### ISSUE TITLE
How to migrate existing pytorch model to torchrec distributed model?

### ISSUE THREAD

**Issue by Ye-Tian-Zero** [meta-pytorch/torchrec#2104]
I know how to deal with model parameters, but not sure how to migrate optimzier states? As generally, torch optimizer is explictly exported by `.state_dict()`, but torchrec's optimizer is fused with the dmp model?

**Comment by henrylhtsang** [comment]
Try dmp.fused_optimizer

You can call state_dict on it

**Comment by Ye-Tian-Zero** [comment]
Thanks, I will take a look at that, close this issue for now.
