### ISSUE TITLE
does torchrec have a container image?

### ISSUE THREAD

**Issue by ywangwxd** [meta-pytorch/torchrec#2287]
It is too painful to setup the environment. I have tried both cuda11.8 and cuda 12.2 environment.
Both of them cannot pass the test. The final error ended in python segmentation error. The following
is screenshot of cuda 12.2 env.

<img width="805" alt="screenshot1" src="https://github.com/user-attachments/assets/a42540ca-fc39-4d2b-a0f9-116b91a4c21c">

**Comment by ywangwxd** [comment]
By the way, I found the real problem is fbgemm, but making fbgemm working is another painful step. So it is better to have a container image.

**Comment by Fizzbb** [comment]
Did you find a solution? I also feel painful just to install torchrec .... @ywangwxd
