### ISSUE TITLE
torchrec inference build error 

### ISSUE THREAD

**Issue by bmedishe** [meta-pytorch/torchrec#231]
Hi 
I am trying to build [torchrec/torchrec/inference](https://github.com/pytorch/torchrec/tree/main/torchrec/inference#readme) , I get this error of "/usr/bin/ld: final link failed: Bad value" with libboost_filesystem.a(operations.o)
```
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libboost_filesystem.a(operations.o): relocation R_X86_64_PC32 against symbol '_ZN5boost10filesystem16filesystem_errorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_4pathESC_NS_6system10error_codeE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```
I got similar error with folly library too , which after building folly(folly built with gcc 9+, g++ 9+)  with -fPIC got fixed. I install libboost using this command line
```./build/fbcode_builder/getdeps.py install-system-deps --recursive```

docker image : pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel
machine : gpu : nvidia tesla v100 , 

Could you kindly help me with debugging this error ?

Thank you
Bhavya

**Comment by s4ayub** [comment]
Hi @bmedishe, we've updated our docs recently with new installation instructions and an updated CMakeLists.txt: https://github.com/pytorch/torchrec/tree/main/torchrec/inference

There is also a server and client example for you to try out.

Please let me know if you have any questions or need any help with the setup.
