### ISSUE TITLE
[Question] How to calculate pooling_factor and num_poolings for torchrec.distributed.planner.types.ParameterConstraints?

### ISSUE THREAD

**Issue by gouchangjiang** [meta-pytorch/torchrec#2416]
To better estimate the GPU memory cost and throughput, I try to specify pooling_factor and num_poolings arguments of [ParameterConstraints](https://github.com/pytorch/torchrec/blob/374b8431157fd6748b70b37d1a8d90af25657606/torchrec/distributed/planner/types.py#L543C7-L543C27) for each table. But I don't know how to calculate these arguments. From the paper [DreamShard](https://proceedings.neurips.cc/paper_files/paper/2022/file/62302a24b04589f9f9cdd5b02c344b6c-Supplemental-Conference.pdf), it seems that we can calculate them from the input of the EmbeddingBagCollection, e.g., keyedJaggedTensor. Could you please give a simple example? I really appreciate any help you can provide.

**Comment by iamzainhuda** [comment]
`pooling_factor` is the average number of rows you're looking up for each sample. take lengths [3, 1, 2] (looking up 3 rows for first batch, 1 row for second, 2 rows for third) for example, the pooling factor would be (3+1+2)/3 = 2. in other words, pooling factor is average number of row lookups for each datapoint you have. so the larger `pooling_factor` the more lookups and more computation you have to do, this will also affect the backward as you have to update more rows in the embeddng table.

`num_poolings` typically tends to be `1.0`, it's the number of "pooling layers" the embeddings will go through like sum, mean, sum. but we just do the operation once. so keeping it at `1.0` is pretty stable.
