### ISSUE TITLE
[typo] typo of torchrec.sparse.jagged_tensor.JaggedTensor

### ISSUE THREAD

**Issue by gouchangjiang** [meta-pytorch/torchrec#2417]
There is a typo of [JaggedTensor](https://pytorch.org/torchrec/torchrec.sparse.html#torchrec.sparse.jagged_tensor.JaggedTensor). The example given shows that the result is `j1 = [[1.0], [], [7.0], [8.0], [10.0, 11.0, 12.0]]`. I tested, it should be `[[1.0], [], [7.0, 8.0], [10.0, 11.0, 12.0]]`. Following is the full python snippet.
```python
values = [
    torch.Tensor([1.0]),
    torch.Tensor(),
    torch.Tensor([7.0, 8.0]),
    torch.Tensor([10.0, 11.0, 12.0]),
]
weights = [
    torch.Tensor([1.0]),
    torch.Tensor(),
    torch.Tensor([7.0, 8.0]),
    torch.Tensor([10.0, 11.0, 12.0]),
]
j1 = JaggedTensor.from_dense(
    values=values,
    weights=weights,
)
print(j1)
```

**Comment by iamzainhuda** [comment]
thanks for that! will fix
