### ISSUE TITLE
Criteo dataset availability

### ISSUE THREAD

**Issue by rllin** [meta-pytorch/torchrec#245]
Is there another source for the criteo data by day?

The links at `http://azuremlsampleexperiments.blob.core.windows.net/criteo/day_0.gz` seem unavailable.

**Comment by s4ayub** [comment]
Using https://labs.criteo.com/2013/12/download-terabyte-click-logs-2/, I ran:

`curl -O http://azuremlsampleexperiments.blob.core.windows.net/criteo/day_{`seq -s ‘,’ 0 1`}.gz`

which resulted in:

```
[1/2]: http://azuremlsampleexperiments.blob.core.windows.net/criteo/day_0‘.gz --> day_0‘.gz
--_curl_--http://azuremlsampleexperiments.blob.core.windows.net/criteo/day_0‘.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: azuremlsampleexperiments.blob.core.windows.net
```

Looks like this issue was brought up with nvidia as well: https://github.com/NVIDIA/DeepLearningExamples/issues/1098

Will see if there's a way to contact criteo about this.

**Comment by rllin** [comment]
@s4ayub have you had any luck?  do you have contacts at criteo?

**Comment by s4ayub** [comment]
@rllin we've contacted criteo from our end but no response as of yet. Will update you on this task when we hear back.

**Comment by victor-paltz** [comment]
Hello everyone, we are on it!
We'll keep you updated about this :)

**Comment by rllin** [comment]
thanks @victor-paltz !  any sense of timeline?

**Comment by victor-paltz** [comment]
ASAP, I will tell you when I have a precise info

**Comment by victor-paltz** [comment]
So, we hopefully should have a solution by the end of the week

**Comment by thomas9t** [comment]
Any work from the folks at Criteo about this? I too ran into this problem yesterday.

**Comment by victor-paltz** [comment]
Work is still ongoing but it shouldn't be long now, sorry for the inconvenience

**Comment by gopikrishnajha** [comment]
@victor-paltz any update on when the link will be up?

**Comment by AGeille** [comment]
Dear all a transition solution has been set up and we are discussing with several partners to set a list of mirror sites. 
The links are the following:
https://storage.googleapis.com/criteo-cail-datasets/day_0.gz
**up to**
https://storage.googleapis.com/criteo-cail-datasets/day_23.gz
Criteo's website is about to be updated
