### ISSUE TITLE
Question about Row-wise Sharding behavior across multiple machines

### ISSUE THREAD

**Issue by whn09** [meta-pytorch/torchrec#2510]
I have a question about the row-wise sharding behavior in TorchRec when running on multiple machines.

My setup:
- Embedding table size: 1.6B rows
- Number of machines: 2
- GPUs per machine: 8 A100 GPUs (16 GPUs in total)
- Sharding strategy: Row-wise sharding

I observed that each GPU gets about 200M rows (1.6B rows per machine, shared among 8 GPUs), rather than 100M rows (1.6B rows divided by 16 GPUs).

This suggests that row-wise sharding is done at machine level first (1.6B/2 = 800M rows per machine), then shared among GPUs within each machine, rather than sharding across all available GPUs directly.

Could someone explain:
1. Is this the expected behavior?
2. What's the rationale behind this design?
3. Which part of the source code controls this sharding behavior?

Thanks in advance!

**Comment by JacoCheung** [comment]
Hi @whn09 , How do you get the local rows ? (200M per rows)?

Could you please check the `plan` of your embedding collection? 

```
model = torchrec.distributed.DistributedModelParallel(ebc, device=torch.device("cuda"))
print(model.plan)
```

**Comment by whn09** [comment]
Hi Jaco,

My output: {'rank:0': {'shard_offsets': [0, 0], 'shard_sizes': [200000000, 16]}, 'rank:1': {'shard_offsets': [200000000, 0], 'shard_sizes': [200000000, 16]}, 'rank:2': {'shard_offsets': [400000000, 0], 'shard_sizes': [200000000, 16]}, 'rank:3': {'shard_offsets': [600000000, 0], 'shard_sizes': [200000000, 16]}, 'rank:4': {'shard_offsets': [800000000, 0], 'shard_sizes': [200000000, 16]}, 'rank:5': {'shard_offsets': [1000000000, 0], 'shard_sizes': [200000000, 16]}, 'rank:6': {'shard_offsets': [1200000000, 0], 'shard_sizes': [200000000, 16]}, 'rank:7': {'shard_offsets': [1400000000, 0], 'shard_sizes': [200000000, 16]}}

**Comment by iamzainhuda** [comment]
If possible can you share your setup code? (or entire sharding plan) Are you running the planner unconstrained? With your shards it looks like it suggests TWRW and not RW

**Comment by whn09** [comment]
> If possible can you share your setup code? (or entire sharding plan) Are you running the planner unconstrained? With your shards it looks like it suggests TWRW and not RW

Hi,

I only have one large embedding table, and I use torchrec_dlrm/dlrm_main.py as referenced code:

https://github.com/facebookresearch/dlrm/blob/main/torchrec_dlrm/dlrm_main.py#L653

Thx!

**Comment by iamzainhuda** [comment]
Can you share the entire sharding plan you generated? I am curious to see the sharding type it as suggested, I believe it has suggested TWRW and not RW

**Comment by Chevolier** [comment]
shared_embedding 
 ParameterSharding(sharding_type='table_row_wise', compute_kernel='fused', ranks=[0, 1, 2, 3, 4, 5, 6, 7], sharding_spec=EnumerableShardingSpec(shards=[ShardMetadata(shard_offsets=[0, 0], shard_sizes=[200000000, 16], placement=rank:0/cuda:0), ShardMetadata(shard_offsets=[200000000, 0], shard_sizes=[200000000, 16], placement=rank:1/cuda:1), ShardMetadata(shard_offsets=[400000000, 0], shard_sizes=[200000000, 16], placement=rank:2/cuda:2), ShardMetadata(shard_offsets=[600000000, 0], shard_sizes=[200000000, 16], placement=rank:3/cuda:3), ShardMetadata(shard_offsets=[800000000, 0], shard_sizes=[200000000, 16], placement=rank:4/cuda:4), ShardMetadata(shard_offsets=[1000000000, 0], shard_sizes=[200000000, 16], placement=rank:5/cuda:5), ShardMetadata(shard_offsets=[1200000000, 0], shard_sizes=[200000000, 16], placement=rank:6/cuda:6), ShardMetadata(shard_offsets=[1400000000, 0], shard_sizes=[200000000, 16], placement=rank:7/cuda:7)]), cache_params=None, enforce_hbm=None, stochastic_rounding=None, bounds_check_mode=None, output_dtype=None)
 
 Hi @iamzainhuda , the above is the entire sharding plan, and it is actually 'table_row_wise'.

**Comment by iamzainhuda** [comment]
Yeah so if you want row wise I suggest adding a `ParameterConstraint` to the table you're sharding to be `ROW_WISE` and then you should see the sharding across all 16 GPUs instead.

**Comment by Chevolier** [comment]
Yes, by adding ParameterConstraints and specify ROW_WISE sharding, the embedding table is sharded across 16 gpus.  Thanks a lot for the help! 

> Yeah so if you want row wise I suggest adding a `ParameterConstraint` to the table you're sharding to be `ROW_WISE` and then you should see the sharding across all 16 GPUs instead.
