### ISSUE TITLE
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'torchrec.sparse.jagged_tensor.JaggedTensor'>

### ISSUE THREAD

**Issue by gouchangjiang** [meta-pytorch/torchrec#2641]
I implemented a subclass of torch.utils.data.Dataset to convert my data into JaggedTensor. If I implemented it in a map-style dataset, there would be an issue as the title. The torchrec and python I am using is v1.0.0, 3.10 respectively. I've attached a reproducible example.
`import torch
from torch.utils.data import Dataset, DataLoader
from torchrec.sparse.jagged_tensor import JaggedTensor

data_1 = [
    torch.Tensor([1.0]),
    torch.Tensor(),
    torch.Tensor([7.0, 8.0]),
    torch.Tensor([10.0, 11.0, 12.0]),
]

data_2 = [
    torch.Tensor([1.0]),
    torch.Tensor(),
    torch.Tensor([7.0, 8.0]),
    torch.Tensor([10.0, 11.0, 12.0]),
]

data_3 = [
    torch.Tensor([1.0]),
    torch.Tensor(),
    torch.Tensor([7.0, 8.0]),
    torch.Tensor([10.0, 11.0, 12.0]),
]

data = [data_1, data_2, data_3]

class MyDataset(Dataset):
   def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        values = self.data[idx]
        sample = JaggedTensor.from_dense(
            values=values
        )
        return sample

dataset = MyDataset(data)
dataloader = DataLoader(dataset, batch_size=3, shuffle=False)

first_sample = dataset[0]
print(f"First Sample: {first_sample}")

for batch_idx, batch_data in enumerate(dataloader):
    print(f"Batch {batch_idx} - Data: {batch_data}")
`

**Comment by sarckk** [comment]
Hi, thanks for flagging this @gouchangjiang. I guess torch.utils.data.Dataset doesn't support JaggedTensor natively. To unblock yourself, could you work with (jagged) lists of tensors in the Dataset and pass in a custom collate fn to create a `JaggedTensor` out of it during data loading? Let me know if this isn't possible and there's a specific use case you'd like to see supported. Thanks!

**Comment by gouchangjiang** [comment]
Yeah, the approach you suggested works. Organize the batched data into values and lengths (of offsets), then convert them to jagged tensor works. Thanks.
