### ISSUE TITLE
Torchrec sharding plan setting

### ISSUE THREAD

**Issue by shan-jiang-faire** [meta-pytorch/torchrec#2642]
I'm using torchrec to make model parallelization. Is that possible to manually setting up a group of sparse features to be sharded in the same machine? For example, I have 3 sparse features A, B and C. They are interact frequently in my model so I'd like them to be in the same GPU to reduce the communication between machines. Is there any way to make it in torchrec?

Thanks very much!

**Comment by sarckk** [comment]
Hi @shan-jiang-faire, I'm assuming these 3 features will be in separate embedding tables? afaik, if you're using the TorchRec planner to generate a sharding plan, there isn't an easy way to enforce all 3 tables will be on the same GPU/rank. However, you can use the `construct_module_sharding_plan` API [[source](https://github.com/pytorch/torchrec/blob/main/torchrec/distributed/sharding_plan.py#L793)] to manually define a sharding plan such that the 3 tables are table-wise sharded on the same rank. 

Example:
```
plan = construct_module_sharding_plan(
  ebc,
  {
     "table_1": table_wise(rank=0),
     "table_2": table_wise(rank=0),
     "table_3": table_wise(rank=0),
  },
)
```

Would that work for your use case?

**Comment by shan-jiang-faire** [comment]
Thank you very much! Yes, they are in separate tables. I think it is what I need here. Let me try it. Thanks again!

**Comment by sarckk** [comment]
@shan-jiang-faire closing this issue for now. Feel free to re-open if your issue isn't resolved.

**Comment by shan-jiang-faire** [comment]
Hi @sarckk, I tried the following config:

```
    train_model = MyTrainModel()
    optimizer_kwargs = {"lr": args.learning_rate}
    apply_optimizer_in_backward(
        torch.optim.Adam,
        train_model.model.sparse_arch.parameters(),
        optimizer_kwargs,
    )
    module_sharding_plan = construct_module_sharding_plan(
        train_model.model.sparse_arch.embedding_bag_collection,
        per_param_sharding={
            "table_0": table_wise(rank=0),
            "table_1": table_wise(rank=0),
            "table_2": table_wise(rank=0),
            "table_3": table_wise(rank=0),
            "table_4": table_wise(rank=0),
            "table_5": table_wise(rank=1),
            "table_6": table_wise(rank=1),
            "table_7": table_wise(rank=1),
            "table_8": table_wise(rank=1),
        },
    )
    model = DistributedModelParallel(
        module=train_model,
        device=device,
        plan=ShardingPlan({"model.sparse_arch.embedding_bag_collection": module_sharding_plan}),
    )
```

But got the following error when trying to run 

```
pipeline.progress(batched_iterator)
```
where pipeline is an _TrainPipelineSparseDist_ instance built from _model_:

```
NotImplementedError: Could not run 'fbgemm::permute_2D_sparse_data' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'fbgemm::permute_2D_sparse_data' is only available for these backends: [CPU, Meta, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradMeta, AutogradNestedTensor, Tracer, AutocastCPU, AutocastXPU, AutocastMPS, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].
```

Any idea what is going wrong here? Thanks very much! Really appreciate your help!

**Comment by shan-jiang-faire** [comment]
Above problem solved by reinstall fbgemm package.
