### ISSUE TITLE
ValueError: All tables in a EmbeddingCollection are required to have same embedding dimension.

### ISSUE THREAD

**Issue by getchebarne** [meta-pytorch/torchrec#294]
Hello,

I noticed there's a possible bug in the EmbeddingCollection API. The [documentation](https://pytorch.org/torchrec/torchrec.modules.html#torchrec.modules.embedding_modules.EmbeddingCollection) lists this example:

```
e1_config = EmbeddingConfig(
    name="t1", embedding_dim=2, num_embeddings=10, feature_names=["f1"]
)
e2_config = EmbeddingConfig(
    name="t2", embedding_dim=3, num_embeddings=10, feature_names=["f2"]
)

ec = EmbeddingCollection(tables=[e1_config, e2_config])

#     0       1        2  <-- batch
# 0   [0,1] None    [2]
# 1   [3]    [4]    [5,6,7]
# ^
# feature

features = KeyedJaggedTensor.from_offsets_sync(
    keys=["f1", "f2"],
    values=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7]),
    offsets=torch.tensor([0, 2, 2, 3, 4, 5, 8]),
)
feature_embeddings = ec(features)
print(feature_embeddings['f2'].values())
tensor([[-0.2050,  0.5478,  0.6054],
[ 0.7352,  0.3210, -3.0399],
[ 0.1279, -0.1756, -0.4130],
[ 0.7519, -0.4341, -0.0499],
[ 0.9329, -1.0697, -0.8095]], grad_fn=<EmbeddingBackward>)
```

However, when trying to run this code, I get the following error:

> ValueError: All tables in a EmbeddingCollection are required to have same embedding dimension.

Why does this happen? As I see it, EmbeddingCollection should be able to have different embedding dimensions for each feature.

**Comment by zyan0** [comment]
I think the exception was added to make the sharding conversion more easier. We can update the docs to make the example tables use the same dim. For different dim support, I think the tricky part is with the sharded implementation. cc @xing-liu

**Comment by xing-liu** [comment]
Yes, that's right. We don't support variable dims sharding for EC.
