### ISSUE TITLE
`torchrec` wheels don't follow the regular PyTorch scheme

### ISSUE THREAD

**Issue by pmeier** [meta-pytorch/torchrec#334]
I'm the author of a [tool that helps installing PyTorch distributions with `pip`](https://github.com/pmeier/light-the-torch). As such, I'm monitoring the custom indices set up by PyTorch. `torchrec` seems to go against the conventions of all other packages. 

Looking at https://download.pytorch.org/whl/nightly/cpu/ I currently get the following

![Screenshot from 2022-05-16 08-23-33](https://user-images.githubusercontent.com/6849766/168532107-a5235aa6-fec4-4b3b-9063-bb2bbf6b37e2.png)

The entry should be just `torchrec`. Things like the channel (`nightly`) or the computation backend (`cpu`, `cu113`, ...) should be done through the initial link. Note that `torch_nightly` and `torchaudio_nightly` are **not** the scheme to adopt here. If you follow the links, the latest entry is from 2019 and only seems to be there for BC.

Speaking of dates, following the `torchrec_nightly` link shows

![Screenshot from 2022-05-16 08-32-30](https://user-images.githubusercontent.com/6849766/168532728-0b9e8fa2-bcbf-432e-8fc4-c04c873d3576.png)

The naming and date scheme differs from other packages. For example yesterdays `torch` nightlies for CPU look like

![Screenshot from 2022-05-16 08-35-10](https://user-images.githubusercontent.com/6849766/168533058-6a233099-bb1e-4c60-b55a-09497cc1215e.png)

It seems `torchrec` for now is a pure Python package and thus does not need to be compiled against multiple computation backends and platforms. Thus, the nightly wheel should look like 

```
torchrec-0.1.0.dev20220516-py3-none-any.whl
```

and hosted for *all* backends. `torchdata` has the same setup:

- https://download.pytorch.org/whl/nightly/cpu/torchdata/
- https://download.pytorch.org/whl/nightly/cu102/torchdata/
- https://download.pytorch.org/whl/nightly/cu113/torchdata/
- https://download.pytorch.org/whl/nightly/cu116/torchdata/

**Comment by YLGH** [comment]
Hey @pmeier thanks for notifying this, the ones that were uploaded were from some tests to test our secret keys - but I'll be sure that our GHAs abide by this 

cc @colin2328

**Comment by colin2328** [comment]
Thanks for raising @pmeier 

 > It seems torchrec for now is a pure Python package and thus does not need to be compiled against multiple computation backends and platforms. Thus, the nightly wheel should look like

This is actually not try right now as current torchrec packages include compiled fbgemm_gpu, which is compiled from C++ . However, we are moving towards this model as fbgemm_gpu release matures, and we can move towards your suggested format


We can follow the conventions you suggested, thanks

**Comment by pmeier** [comment]
> This is actually not try right now as current torchrec packages include compiled fbgemm_gpu, which is compiled from C++ . 

Huh? If you distribute compiled binaries, how can you have `*-any.whl` wheels? That indicates that the binary [runs on *any* CPU architecture](https://peps.python.org/pep-0491/#file-name-convention).

**Comment by colin2328** [comment]
ah, what I meant was that we are compiling CUDA. You are right in that we aren't compiling against different CPU backends/platforms

**Comment by YLGH** [comment]
@pmeier Closing this issue as we're now only uploading to PyPi

**Comment by pmeier** [comment]
Just to make sure I understand correctly: the nightly builds are [uploaded to PyPI](https://pypi.org/project/torchrec-nightly/#history) and so everything on the official index will no longer be relevant, correct?
