### ISSUE TITLE
Checkpointing / Serialization best practices

### ISSUE THREAD

**Issue by lukepfister** [meta-pytorch/torchrec#346]
Are there best practices around checkpointing (and more generally, serializing) torchrec models?  I'm thinking in particular about an EmbeddingBagCollection that is sharded across multiple devices.

**Comment by dstaay-fb** [comment]
The public api for accessing internal state via state_dict method.  For sharded model case, you would need to call on all devices in the respective Process, and the state_dict for that Process would contain a ShardedTensor if a shard for a given parameter is on that device.

Example in tests on how to access internal state: https://github.com/pytorch/torchrec/blob/7e33aaf857b9a7cf72e13a15a50a93b46dcb0fe6/torchrec/distributed/tests/test_model_parallel.py#L570

To checkpoint, you want to serialize the output of the state_dict call, then deserialize, reload via load_state_dict call.   Effectively you need distributed checkpointing w/ ShardedTensor support, which is in active development tin PyTorch right now: https://github.com/pytorch/pytorch/pull/76123

**Comment by colin2328** [comment]
3 approaches

1) if 'resharding' is not needed, simply using the default torch.load() torch.save() apis of each ranks DMP.state_dict()
2) using save_state_dict using the shardedTensor APIs linked above  by @dstaay-fb  if 'resharding' is needed

3) Use torchsnapshot- see https://github.com/facebookresearch/torchsnapshot/blob/main/examples/torchrec_example.py, which uses ShardedTensor checkpointing APIs

We recommend 3)
