### ISSUE TITLE
Loading pretrained Embeddings into an EmbeddingBagCollection

### ISSUE THREAD

**Issue by noahshpak** [meta-pytorch/torchrec#355]
Hello! I am curious if there are best practices for loading in embeddings that need to be sharded across multiple GPUs? 

As an example
* I have a large corpus user embeddings published by another system
* I'd like these to be loaded once and sharded across GPUs for training

Thank you for any guidance!

**Comment by colin2328** [comment]
We suggest 
1) constructing a model using torchrec (wrapping in DMP) per rank
2) creating a state_dict containing a single (unsharded) EBC with the desired user_embeddings in the values
3) create a function to map the single (unsarded) state_dict to each ranks state_dict as it looks for the sharded model
4) load_state_dict() for each rank, using the mapping function

We plan on adding examples that showcase something like this (particularly 1, 3 and 4). We also plan on adding components to make this process simpler in the coming month cc @yifuwang  @kumpera  @zyan0

**Comment by lukepfister** [comment]
Thanks!

For step 2: we want to avoid loading the data N_RANK times.  can the data be loaded on rank 0 and then shared with the other ranks?

**Comment by noahshpak** [comment]
@colin2328 thanks for sketching it out! Just to clarify, when I shard a dummy table I a `state_dict` like this for 2 gpus:
```OrderedDict([('embedding_bags.tweet_emb.weight', ShardedTensor(ShardedTensorMetadata(shards_metadata=[ShardMetadata(shard_offsets=[0, 0], shard_sizes=[50000000, 100], placement=rank:0/cuda:0), ShardMetadata(shard_offsets=[50000000, 0], shard_sizes=[50000000, 100], placement=rank:1/cuda:1)], size=torch.Size([100000000, 100]), tensor_properties=TensorProperties(dtype=torch.float32, layout=torch.strided, requires_grad=False, memory_format=torch.contiguous_format, pin_memory=False))))])```

When I then `load_state_dict()` for each rank could I simply set the tensor via
```python
state_dict = torch.load(state_dict_path)
t = load(path_to_my_ranks_shard)
# need to match device from state_dict metadata
state_dict["embedding_key"]._local_shards[0].tensor = t 
ebc = EmbeddingBagCollection(...)  # same configuration
ebc = ebc.load_state_dict(modified_state_dict)
```

**Comment by xing-liu** [comment]
If you want to load a state dict saved by N GPUs on M GPUs You need a checkpointing backend that supports resharding (map N GPUs to M GPUs). TorchRec's state dict returns ShardedTensor for embedding tables, which contains sharding metadata and can be used to implement resharding backend. If N==M, you don't need resharding and no redundant data will be loaded since the state dict is also sharded.

**Comment by alykhantejani** [comment]
@colin2328 just checking my understanding is correct. There are two general ways to do the checkpointing. 
1) all_reduce model state to one device and then save (whilst storing some metadata about the sharding plan)
2) use the shar checkpointing stuff in pytorch master (https://github.com/pytorch/pytorch/blob/88fca3be5924dd089235c72e651f3709e18f76b8/torch/distributed/_shard/checkpoint/state_dict_saver.py#L89) to store each shard of a sharded tensor as separate files?

**Comment by noahshpak** [comment]
@colin2328 @xing-liu Thanks for the comments. I have a hacky gist that meets our goals: https://gist.github.com/noahshpak/ebb6a84a1bb2371f49c67030757bc37b

I had to patch in some classes to make the Sharders work as expected with inheritance since there are so many lookups by `type(class)`. Does anything look incorrect here to you?

**Comment by yifuwang** [comment]
Hi @noahshpak, please see [this gist](https://gist.github.com/yifuwang/e0556d51196c5547ce28348ca936f6fd) for an example of initializing `EmbeddingBagCollection` from a non-sharded, pretrained embedding. The gist also includes a small share memory utility so the pretrained embedding only needs to be loaded once on every host.

**Comment by colin2328** [comment]
@noahshpak , I'm going to close this issue, hopefully the gist solves the issue (we will consider putting this gist into examples)
