### ISSUE TITLE
Torchscript tracing / scripting best practices

### ISSUE THREAD

**Issue by zhuzilin** [meta-pytorch/torchrec#417]
Hi there! I'm trying to deploy a torchrec model with torchscript and I wonder what's the best practice for it.

From my experience, when tracing the model, we cannot get a script model that supports dynamic batch size. The reason for this is that the `lengths_per_key` is of type `List[int]`, which will be regard as constant during tracing. Therefore a workaround I made is passing a `torch.Tensor` as `length_per_key` and change here:
https://github.com/pytorch/torchrec/blob/e8d9755f2e2766ae493c0c497f5ef1187cec0df0/torchrec/sparse/jagged_tensor.py#L579
into:
```python
        # Note here `length_per_key` is a Tensor
        offset_per_key = torch.cumsum(length_per_key, dim=0)
        values_list = torch.tensor_split(values, offset_per_key)
```
I wonder whether it's a good idea to support `Tensor` type `length_per_key` and if there is a better way to support dynamic batch size.

Thank you for your time on this issue :)

**Comment by YLGH** [comment]
hey @zhuzilin , looking into this, but have a couple of Qs:

1. By dynamic batch size do you mean that each rank has a different batch size, or between iterations the batch sizes change?
2. Are you using torch.deploy w/ torchscript to do this? 
3. Are you working on a larger project, or just experiment with TorchRec?

**Comment by colin2328** [comment]
do you plan on serving on CPU or GPU?

We do have an example of torch deploy inference here https://github.com/pytorch/torchrec/tree/main/torchrec/inference
As previews, 
We're working on a single GPU inference example (including TRT)
We're also working on a single CPU inference example (torchscript based)

**Comment by zhuzilin** [comment]
@YLGH 
> 1. By dynamic batch size do you mean that each rank has a different batch size, or between iterations the batch sizes change?

It's similar to "between iterations the batch sizes change". During inference, we will normally set a max_batch_size and batching the coming requests into batch size beween [1, max_batch_size] to reduce latency.

> 2. Are you using torch.deploy w/ torchscript to do this?

I'm not using torch.deploy at the moment. The  reason is that I'm trying to deploy torchrec model into our existing system and it's would be much better if I can reuse the existing infra. Introducing torch.deploy would cause a huge change in our online environment (even from recompiling cpython...) and make this a harder attempt. I'm afraid it's the same for most team that have interest for torchrec.

> 3. Are you working on a larger project, or just experiment with TorchRec?

larger project

**Comment by zhuzilin** [comment]
@colin2328 
> do you plan on serving on CPU or GPU?

GPU

> We do have an example of torch deploy inference here

As I mentioned in the comment above, I'm afraid it's hard for my team to adopt torch.deploy at the moment.

And also, I don't quite understand how the current inference example load trained weights from checkpoints...
I have been trying the best practice to load checkpoints from https://github.com/pytorch/torchrec/issues/346 (using the distributed checkpointing w/ ShardedTensor support because I need to train with multiple GPUs while do inference on one GPU), and found several issues with the current ShardedTensor checkpoint, which I made an issue and PRs here: https://github.com/pytorch/pytorch/issues/79016

> We're working on a single GPU inference example

That's great! I wonder if the GPU inference example could be w/o torch.deploy? Thank you~

**Comment by zyan0** [comment]
@zhuzilin

we do plan to have an example showcasing trainer side transformation and publishing into a torchscripted model for inference.

maybe we can have a short meeting regarding best practices for GPU inference for TorchRec models. we should also see whether the torch::deploy approach would be feasible in a longer time frame. cc @s4ayub

**Comment by zhuzilin** [comment]
@zyan0 I'd love to have a short meeting! My colleagues and I are available in 10:00 - 21:00 UTC+8 from Monday to Friday :)

**Comment by colin2328** [comment]
Great idea, @zyan0 

@zhuzilin -> our team (torchrec) is available next week Wed afternoon (between 1pm - 5pm PST), and Friday morning and afternoon (10am - 5pm PST).

If you are flexible, let's say 1pm-2pm PST Wed 6/15? Is [zhuzilinallen@gmail.com](mailto:zhuzilinallen@gmail.com) the best email to send the invite to?

**Comment by zhuzilin** [comment]
@colin2328
It would better if we could settle the meeting at 10am-11am PST Friday morning, as 1pm PST is around 4am in our time zone. And could you send the invitation to zilinzhu@tencent.com? Thank you!

**Comment by colin2328** [comment]
@zhuzilin yes, how about we do 8am PST (11 pm Beijing time) instead? We could to Thursday morning PST (your Thursday night) or Friday morning PST (your Friday night). I assume you would prefer your Thursday night, and I'll send out the invite, hopefully that works for you

**Comment by zhuzilin** [comment]
@colin2328 Thursday night is good for us and thank you for the early meeting! I've forwarded the email to my colleagues. See you this Thursday:)

**Comment by colin2328** [comment]
We do not recommend scripting the entire model with TorchRec. Instead, we recommend scripting the non embedding layers only. See https://github.com/pytorch/torchrec/blob/main/examples/inference/dlrm_predict_single_gpu.py#L80 for an example of this (fx -> TRT lowering here, but the principle is the same).

Unsharded embedidng modules are scriptable, but sharded will not be

Closing this comment for now as we are continuing collab offline
