### ISSUE TITLE
Could not run 'fbgemm::block_bucketize_sparse_features' with arguments from the 'CUDA' backend.

### ISSUE THREAD

**Issue by rllin** [meta-pytorch/torchrec#423]
I'm hitting this on the latest nightly.  Happy to provide a repro, but perhaps obvious.  was not seeing this on nightly from May 20th

**Comment by YLGH** [comment]
Hey @rllin, could you help provide the cmds you used to install pytorch/torchrec (including conda set up)?

**Comment by rllin** [comment]
we had an unpinned install directly from nightly repo

```
pip install --no-cache-dir --pre torchrec_nightly -f https://download.pytorch.org/whl/nightly/torchrec_nightly/index.html
```

when i pinn it to the May 20th version, everything is fine.

**Comment by YLGH** [comment]
@rllin do you happen to know which pytorch version you're using? There are some known issues of using pytorch stable w/ torchrec nightly, 

the latest torchrec-nightly is working for me with pytorch-nightly

**Comment by rllin** [comment]
@YLGH `1.12.0.dev20220520`

is it worth bumping both torch and torchrec to latest nightly of both?  or is there a less recent nightly you'd recommend

**Comment by colin2328** [comment]
@rllin  , I believe this issue should be mitigated (both in latest nightly and stable). Please reopen (or create new issue) if this issue re-appears
