### ISSUE TITLE
TorchArrow documentation links broken

### ISSUE THREAD

**Issue by damianr99** [meta-pytorch/torchrec#486]
On https://github.com/pytorch/torchrec/tree/main/examples/torcharrow the link 'torcharrow.functional Doc' no longer works because the TorchArrow repo has moved recently.  The existing link https://facebookresearch.github.io/torcharrow/functional.html#recommendation-operations should be updated with https://pytorch.org/torcharrow/beta/functional.html#recommendation-operations

**Comment by YLGH** [comment]
Thanks! 

Updated in 

https://github.com/pytorch/torchrec/pull/496
