### ISSUE TITLE
Decouple Table batching + optimizer fusion (module/op level) w/ Sharding

### ISSUE THREAD

**Issue by colin2328** [meta-pytorch/torchrec#505]
Publicly linking our project proposal for API decomposition, see https://docs.google.com/document/d/1T8oZ8zKbgHuy7q0rkpiyJC5fRUiRugR7oWk799qgFjk/edit#

Feel free to comment directly in the doc.

cc @YLGH  @divchenko @zhuzilin

**Comment by YLGH** [comment]
Let's close this issue since now we have composable APIs + apply_optimizer_in_backward? @colin2328
