### ISSUE TITLE
FBGEMM_gpu issue from both pip install (stable and nightly) and install from source

### ISSUE THREAD

**Issue by HQ01** [meta-pytorch/torchrec#551]
Hi! I'm trying to install Torchrec and is currently having issue with the FBGEMM dependency. I tried pip install both stable and nightly build following the instruction at https://github.com/pytorch/torchrec#installations , both give me error
`OSError: /home/user/anaconda3/envs/torchrec/lib/python3.10/site-packages/fbgemm_gpu/fbgemm_gpu_py.so: undefined symbol: _ZNR5torch7Library4_defEON3c1014FunctionSchemaEPNS1_12OperatorNameE`.

I also tried building from source, and it gave error

`Installed /home/ec2-user/anaconda3/envs/torchrec/lib/python3.10/site-packages/torchrec-0.2.0-py3.10.egg
Processing dependencies for torchrec==0.2.0
Searching for fbgemm-gpu
Reading https://pypi.org/simple/fbgemm-gpu/
No local packages or working download links found for fbgemm-gpu
error: Could not find suitable distribution for Requirement.parse('fbgemm-gpu')`
when `python setup.py install develop`

Any help/suggestion on how to fix this? Thank you so much in advance!

**Comment by HQ01** [comment]
Update -- the closest I can get right now is 1) build torchrec from source then 2) build FBGEMM from source. Then I can import fbgemm_gpu, but importing torchrec will give me 

  File "/home/ec2-user/SageMaker/custom-miniconda/miniconda/envs/torchrec/lib/python3.10/site-packages/torchrec-0.2.0-py3.10.egg/torchrec/__init__.py", line 8, in <module>
    import torchrec.distributed  # noqa
  File "/home/ec2-user/SageMaker/custom-miniconda/miniconda/envs/torchrec/lib/python3.10/site-packages/torchrec-0.2.0-py3.10.egg/torchrec/distributed/__init__.py", line 36, in <module>
    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
  File "/home/ec2-user/SageMaker/custom-miniconda/miniconda/envs/torchrec/lib/python3.10/site-packages/torchrec-0.2.0-py3.10.egg/torchrec/distributed/model_parallel.py", line 20, in <module>
    from torchrec.distributed.embedding import EmbeddingCollectionSharder
  File "/home/ec2-user/SageMaker/custom-miniconda/miniconda/envs/torchrec/lib/python3.10/site-packages/torchrec-0.2.0-py3.10.egg/torchrec/distributed/embedding.py", line 29, in <module>
    from torchrec.distributed.embedding_sharding import (
  File "/home/ec2-user/SageMaker/custom-miniconda/miniconda/envs/torchrec/lib/python3.10/site-packages/torchrec-0.2.0-py3.10.egg/torchrec/distributed/embedding_sharding.py", line 20, in <module>
    from torchrec.distributed.embedding_types import (
  File "/home/ec2-user/SageMaker/custom-miniconda/miniconda/envs/torchrec/lib/python3.10/site-packages/torchrec-0.2.0-py3.10.egg/torchrec/distributed/embedding_types.py", line 14, in <module>
    from fbgemm_gpu.split_table_batched_embeddings_ops import EmbeddingLocation
ModuleNotFoundError: No module named 'fbgemm_gpu.split_table_batched_embeddings_ops'

**Comment by YLGH** [comment]
hey @HQ01,

which version of PyTorch are you using? 
If you're using pytorch stable, then I think only fbgemm stable will work with it
If pytorch nightly, then fbgemm nightly,
but if you're using a version earlier than stable, then you'll have to use a version < 0.2.0

Also I don't know if python 3.10 is "officially" supported (just 3.7, 3.8, 3.9 in my mind). I'm likely wrong here, but worth trying out

**Comment by HQ01** [comment]
Hi @YLGH thanks for the quick reply! I'm using torch 1.12.0. Both FBGEMM and torchrec are built from source with the latest main branch -- I guess that mean they are nightly then?

I also just found out the release note of torchrec 0.2.0 at https://github.com/pytorch/torchrec/releases/tag/v0.2.0. However, `pip install torchrec==0.2.0` will give error `No matching distribution found for fbgemm-gpu`, so it default back to install torchrec 0.1.0, which has the above mentioned FBGEMM issue of `OSError: /home/user/anaconda3/envs/torchrec/lib/python3.10/site-packages/fbgemm_gpu/fbgemm_gpu_py.so: undefined symbol: _ZNR5torch7Library4_defEON3c1014FunctionSchemaEPNS1_12OperatorNameE`. 

My pip is set up with indexes https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com

**Comment by HQ01** [comment]
Update: I also tried downloading the release version of code of torchrec 0.2.0 and FBGEMM 0.2.0. Couldn't build FBGEMM, can build torchrec 0.2.0 from source only if comment out FBGEMM dependency, which makes it still unusable.

Am I missing something in my pip setup to find fbgemm-gpu, or fbgemm is not discoverable as of now? I think the best solution might be just to fix this `No matching distribution found for fbgemm-gpu` issue, and `pip install torchrec==0.2.0`

**Comment by YLGH** [comment]
@HQ01 to help us reproduce, can you create a new conda environment (with python 3.7) and try the steps again? And also forward the installation commands you used, thanks! 

Also it may be worth cross-posting this on FBGEMM's repo https://github.com/pytorch/FBGEMM/tree/main/fbgemm_gpu,

**Comment by HQ01** [comment]
@YLGH no problem!

**Comment by HQ01** [comment]
@YLGH Yeah I think you are right! Switching to python 3.7 works. I guess the issue is with Python version, and 3.10 is not supported right now. Thank you so much for the help!

**Comment by HQ01** [comment]
Closing the issue as it's been resolved.
