### ISSUE TITLE
fbgemm_gpu_py.so not found

### ISSUE THREAD

**Issue by lukepfister** [meta-pytorch/torchrec#557]
Hi team, I'm trying to use torchrec-nightly with torch 1.12 and CUDA 11.2.  But when I import torchrec, I get the following:
```
>>> import torchrec
File fbgemm_gpu_py.so not found
```

A similar issue was reported on the DLRM issue tracker https://github.com/facebookresearch/dlrm/issues/256.  Any ideas?

**Comment by YLGH** [comment]
If you're using torch 1.12 from stable you'll need to install torchrec 0.2.0 from stable (and also fbgemm 0.2.0 from stable), 

to use torchrec-nightly, use the nightly version of pytorch

**Comment by ammaryasirnaich** [comment]
I am having the same issue `fbgemm_gpu_py.so not found`, I am installing it with CUDA 11.6 and Pytorch 1.12.

**Comment by YLGH** [comment]
> I am having the same issue `fbgemm_gpu_py.so not found`, I am installing it with CUDA 11.6 and Pytorch 1.12.

Are you installing TorchRec nightly or from stable?

**Comment by ammaryasirnaich** [comment]
Stable

**Comment by YLGH** [comment]
> Stable

could help you provide the cmds you used to install from scratch (including pytorch and cuda installation?

**Comment by ammaryasirnaich** [comment]
Actually, I did "pip install torchrec" and "pip install fbgemm-gpu". After that, i tried to import torchrec

**Comment by ammaryasirnaich** [comment]
Regarding the PyTorch and Cuda installation i am using the Nvidia docker container`  nvcr.io/nvidia/pytorch:22.04-py3`

**Comment by ammaryasirnaich** [comment]
@YLGH did you find any clue what is causing the error?

**Comment by YLGH** [comment]
@ammaryasirnaich most likely there's a package mismatch between your torch version and fbgemm. It's you have multiple versions installed and may be using another version of torch.

It's difficult to pin point the reason without knowing what your environment looks like,

Could you list the versions of torch/fbgemm you're using? e.g.

import torch
print(torch.__version__)?

**Comment by ammaryasirnaich** [comment]
These are the detail environmental setup on which i am having this issue along with **fbgemm=(0.2.0)**

```
Python: 3.8.13 | packaged by conda-forge | [GCC 10.3.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3080
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.6, V11.6.124
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.0a0+bd13bc6
PyTorch compiling details: PyTorch built with:
  - GCC 9.4
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash N/A)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
  - CuDNN 8.4
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.4.0, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS=-fno-gnu-unique -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.0a0
OpenCV: 4.5.5

```

**Comment by YLGH** [comment]
> These are the detail environmental setup on which i am having this issue along with **fbgemm=(0.2.0)**
> 
> ```
> Python: 3.8.13 | packaged by conda-forge | [GCC 10.3.0]
> CUDA available: True
> GPU 0: NVIDIA GeForce RTX 3080
> CUDA_HOME: /usr/local/cuda
> NVCC: Cuda compilation tools, release 11.6, V11.6.124
> GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
> PyTorch: 1.12.0a0+bd13bc6
> PyTorch compiling details: PyTorch built with:
>   - GCC 9.4
>   - C++ Version: 201402
>   - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
>   - Intel(R) MKL-DNN v2.5.2 (Git Hash N/A)
>   - OpenMP 201511 (a.k.a. OpenMP 4.5)
>   - LAPACK is enabled (usually provided by MKL)
>   - NNPACK is enabled
>   - CPU capability usage: AVX2
>   - CUDA Runtime 11.6
>   - NVCC architecture flags: -gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
>   - CuDNN 8.4
>   - Magma 2.5.2
>   - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.4.0, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS=-fno-gnu-unique -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 
> 
> TorchVision: 0.13.0a0
> OpenCV: 4.5.5
> ```

is this fbgemm=(0.2.0) the nightly version or the stable?

can you show

conda list | grep fbgemm
conda list | grep torch
pip list | grep fbgemm
pip list | grep torch

**Comment by ammaryasirnaich** [comment]
```
> pip list | grep fbgemm
fbgemm-gpu                    0.2.0

```
```
> pip list | grep torch
pytorch-quantization          2.1.2
torch                         1.12.0a0+bd13bc6
torch-tensorrt                1.1.0a0
torchmetrics                  0.9.3
torchrec                      0.2.0
torchtext                     0.13.0a0
torchvision                   0.13.0a0
torchx-nightly                2022.8.15
```

**Comment by YLGH** [comment]
> ```
> > pip list | grep fbgemm
> fbgemm-gpu                    0.2.0
> ```
> 
> ```
> > pip list | grep torch
> pytorch-quantization          2.1.2
> torch                         1.12.0a0+bd13bc6
> torch-tensorrt                1.1.0a0
> torchmetrics                  0.9.3
> torchrec                      0.2.0
> torchtext                     0.13.0a0
> torchvision                   0.13.0a0
> torchx-nightly                2022.8.15
> ```

1.12.0a0+bd13bc6 looks like the stable version of torch, 
if fbgemm-gpu 0.2.0 is the stable version you shouldn't be having an issue. 

I'd also recommend cross posting to the fbgemm folks, https://github.com/pytorch/FBGEMM/tree/main/fbgemm_gpu

**Comment by ammaryasirnaich** [comment]
> > ```
> > > pip list | grep fbgemm
> > fbgemm-gpu                    0.2.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > > pip list | grep torch
> > pytorch-quantization          2.1.2
> > torch                         1.12.0a0+bd13bc6
> > torch-tensorrt                1.1.0a0
> > torchmetrics                  0.9.3
> > torchrec                      0.2.0
> > torchtext                     0.13.0a0
> > torchvision                   0.13.0a0
> > torchx-nightly                2022.8.15
> > ```
> 
> 1.12.0a0+bd13bc6 looks like the stable version of torch, if fbgemm-gpu 0.2.0 is the stable version you shouldn't be having an issue.
> 
> I'd also recommend cross posting to the fbgemm folks, https://github.com/pytorch/FBGEMM/tree/main/fbgemm_gpu

Sure i will post the issue to the fbgemm fellows
