### ISSUE TITLE
Question about EmbeddingBoundsCheck

### ISSUE THREAD

**Issue by HQ01** [meta-pytorch/torchrec#575]
Hi! I encountered logs like

`EmbeddingBoundsCheck: (at least one) Out of bounds access for batch: 26, table: 6, bag element: 0, idx: 10, num_rows: 10, indices_start: 1466, indices_end: 1467, T: 12, B: 64, b_t: 410. Setting idx to zero.` when modifying the two tower retrieval example to fit our use case. This log appears in running `TrainPipelineSparseDist.progess()` but doesn't show up for all iterations. It's also always about `table 6`. Currently I'm only running on a single GPU single host environment.

Some other sample logs:

`EmbeddingBoundsCheck: (at least one) Out of bounds access for batch: 54, table: 6, bag element: 0, idx: 10, num_rows: 10, indices_start: 1413, indices_end: 1414, T: 12, B: 64, b_t: 438. Setting idx to zero.`

`EmbeddingBoundsCheck: (at least one) Out of bounds access for batch: 44, table: 6, bag element: 0, idx: 10, num_rows: 10, indices_start: 1364, indices_end: 1365, T: 12, B: 64, b_t: 428. Setting idx to zero.`

Could the team help shed some light on what this log means? I tried modifying an EmbeddingBagConfig's `num_embeddings` to be significantly smaller than the max possible index in KeyedJaggedTensor, and it will throw error right away. I also couldn't find where this log line is from in torchrec source code.

Many thanks in advance! Great job on writing up those examples by the way :)

**Comment by HQ01** [comment]
Quick update -- I think I figured out why it happened, but still not sure where this log is from

I have one `EmbeddingBagConfig` with `num_embedding` smaller than the max possible ID.

**Comment by HQ01** [comment]
If I just compute the forward pass with

ebc = an_ebc_with_too_small_num_embeddings
dataPipe = iter(DataPipe())
model = SomeNet(ebc)
example = next(dataPipe)
model(example)

it will give runtime error `RuntimeError: Index 0 is out of bounds: 10, range 0 to 10`

However, when using `TrainPipelineSparseDist.progress` instead, it will give the log above

Is the out of bound runtime error get handled / muted somewhere potentially?

**Comment by YLGH** [comment]
Hey @HQ01 , the error is coming from 

https://github.com/pytorch/FBGEMM/blob/main/fbgemm_gpu/fbgemm_gpu/split_table_batched_embeddings_ops.py#L224

it looks like we don't set this, so it's just WARNING

https://github.com/pytorch/torchrec/blob/main/torchrec/distributed/batched_embedding_kernel.py#L405

**Comment by HQ01** [comment]
Ahh i see, thanks @YLGH !
