### ISSUE TITLE
RuntimeError: No such operator fbgemm::jagged_to_padded_dense error on google colab

### ISSUE THREAD

**Issue by rishabhdhenkawat** [meta-pytorch/torchrec#585]
Splitting
<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7fbb025db450>
Sampling negative items
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/torch/_ops.py](https://localhost:8080/#) in __getattr__(self, op_name)
    197         try:
--> 198             op, overload_names = torch._C._jit_get_operation(qualified_op_name)
    199         except RuntimeError as e:

RuntimeError: No such operator fbgemm::jagged_to_padded_dense

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
13 frames
[/usr/local/lib/python3.7/dist-packages/torch/_ops.py](https://localhost:8080/#) in __getattr__(self, op_name)
    200             # Turn this into AttributeError so getattr(obj, key, default)
    201             # works (this is called by TorchScript with __origin__)
--> 202             raise AttributeError(f"'_OpNamespace' object has no attribute '{op_name}'") from e
    203 
    204         # let the script frontend know that op is identical to the builtin op

AttributeError: '_OpNamespace' object has no attribute 'jagged_to_padded_dense'

**Comment by s4ayub** [comment]
Can you link which colab you're using?

**Comment by rishabhdhenkawat** [comment]
https://colab.research.google.com/drive/1IUorPZUL9eYPugyr64S-d6fmpUPsj0BT?usp=sharing

**Comment by colin2328** [comment]
@rishabhdhenkawat 
please try >>> import torch
>>> torch.ops.jagged_to_padded_dense

If you don't have that, something is wrong in your fbgemm_gpu install

**Comment by YLGH** [comment]
closing issue for lack of update

@rishabhdhenkawat  please open a new issue if you continue to run into this issue

**Comment by jason-wang-discord** [comment]
Tried `!pip3 install "fbgemm-gpu>=0.8.0" --extra-index-url https://pypi.org/simple` and install latest version of fbgemm, it works. In my case, its 1.3.0
