### ISSUE TITLE
Retrieval task and bruteForce prediction

### ISSUE THREAD

**Issue by Asanoci** [meta-pytorch/torchrec#613]
Hello,

I am wondering how to migrate my model from _tensorflow_recommenders_ to pytorch _torchRec_, but I couldn't find the equivalent of the Retrival tasks and bruteForce predictions in the documentation.

Are there functions created for that ? Or one should code them from scratch ?

If it already exists and i didn't see it, sorry for that.

Thank you for your help :)

**Comment by YLGH** [comment]
@Asanoci  we have an example of a retrieval model here, PTAL

https://github.com/pytorch/torchrec/tree/main/examples/retrieval

I'm not familiar with the bruteForce prediction model, could you help link it? I don't think we'd have this customly built model,  but should be possible w/ our embedding module primitives

**Comment by YLGH** [comment]
@Asanoci, does this help resolve your issue? If so, I will close the issue

**Comment by ge0405** [comment]
@Asanoci  Since we did not hear back from you, I am marking this issue closed. Feel free to re-open the issue if you have any questions.
