### ISSUE TITLE
Profiler doens't report Memcpy when using FUSED_UVM

### ISSUE THREAD

**Issue by yunoJ** [meta-pytorch/torchrec#622]
Hi team,

I'm running dlrm with all tables in FUSED_UVM type. The table sizes are modified so that they can't be run with FUSED embedding types. My understanding of FUSED_UVM is that every embedding accesses should be directed to CPU DRAM. However, I'm not seeing any CUDA MempcyH2D during SparseArch in training traces. Am I mistaken with what FUSED_UVM is? If so, what is FUSED_UVM embedding type?

**Comment by xing-liu** [comment]
FUSED_UVM uses the CUDA unified memory (https://developer.nvidia.com/blog/unified-memory-cuda-beginners/), so it is normal not to see any explicit H2D memory copies.

**Comment by yunoJ** [comment]
Thanks for the prompt answer.
