### ISSUE TITLE
pytorch nightly + torchrec nightly not compatible with fbgemm for test_installation.py

### ISSUE THREAD

**Issue by ZhengHongming888** [meta-pytorch/torchrec#649]
Hi, i installed the following version for packages as readme. 

cudatoolkit                       11.3.1                       h2bc3f7f_2
fbgemm-gpu-nightly        2022.9.19                pypi_0    pypi
pytorch                             1.13.0.dev20220919     py3.7_cpu_0    pytorch-nightly
torchmetrics                     0.9.3                        pypi_0    pypi
torchrec-nightly               2022.9.19                pypi_0    pypi
torchx-nightly                  2022.9.19                pypi_0    pypi

when i run the pytorch test_installation.py as 
torchx run -s local_cwd dist.ddp -j 1x2 --gpu 2 --script test_installation.py

There are the following error happened. 

===============
torchx 2022-09-19 22:44:35 INFO     Log directory not set in scheduler cfg. Creating a temporary log dir that will be deleted on exit. To preserve log directory set the `log_dir` cfg option
torchx 2022-09-19 22:44:35 INFO     Log directory is: /tmp/torchx_32yqu363
local_cwd://torchx/test_installation-jclxjg6pxm1wqc
torchx 2022-09-19 22:44:35 INFO     Waiting for the app to finish...
test_installation/0 WARNING:__main__:
test_installation/0 *****************************************
test_installation/0 Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
test_installation/0 *****************************************
test_installation/0 [0]:libc10_cuda.so: cannot open shared object file: No such file or directory
test_installation/0 [1]:libc10_cuda.so: cannot open shared object file: No such file or directory
test_installation/0 [0]:Traceback (most recent call last):
test_installation/0 [1]:Traceback (most recent call last):
test_installation/0 [0]:  File "/usr/local/lib/python3.7/site-packages/torch/_ops.py", line 492, in __getattr__
test_installation/0 [0]:    op, overload_names = torch._C._jit_get_operation(qualified_op_name)
test_installation/0 [0]:RuntimeError: No such operator fbgemm::jagged_2d_to_dense
test_installation/0 [0]:
test_installation/0 [0]:The above exception was the direct cause of the following exception:
test_installation/0 [0]:
test_installation/0 [0]:Traceback (most recent call last):
test_installation/0 [1]:  File "/usr/local/lib/python3.7/site-packages/torch/_ops.py", line 492, in __getattr__
test_installation/0 [0]:  File "test_installation.py", line 16, in <module>
test_installation/0 [1]:    op, overload_names = torch._C._jit_get_operation(qualified_op_name)
test_installation/0 [0]:    from torchrec import EmbeddingBagCollection, KeyedJaggedTensor
test_installation/0 [0]:  File "/hongming/new_torchrec/torchrec/torchrec/__init__.py", line 8, in <module>
test_installation/0 [0]:    import torchrec.distributed  # noqa
test_installation/0 [0]:  File "/hongming/new_torchrec/torchrec/torchrec/distributed/__init__.py", line 36, in <module>
test_installation/0 [0]:    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
test_installation/0 [0]:  File "/hongming/new_torchrec/torchrec/torchrec/distributed/model_parallel.py", line 20, in <module>
test_installation/0 [0]:    from torchrec.distributed.embedding import EmbeddingCollectionSharder
test_installation/0 [1]:RuntimeError: No such operator fbgemm::jagged_2d_to_dense
test_installation/0 [0]:  File "/hongming/new_torchrec/torchrec/torchrec/distributed/embedding.py", line 30, in <module>
test_installation/0 [1]:
test_installation/0 [0]:    from torchrec.distributed.embedding_sharding import (
test_installation/0 [1]:The above exception was the direct cause of the following exception:
test_installation/0 [0]:  File "/hongming/new_torchrec/torchrec/torchrec/distributed/embedding_sharding.py", line 15, in <module>
test_installation/0 [1]:
test_installation/0 [0]:    from torchrec.distributed.dist_data import (
test_installation/0 [1]:Traceback (most recent call last):
test_installation/0 [0]:  File "/hongming/new_torchrec/torchrec/torchrec/distributed/dist_data.py", line 16, in <module>
test_installation/0 [1]:  File "test_installation.py", line 16, in <module>
test_installation/0 [1]:    from torchrec import EmbeddingBagCollection, KeyedJaggedTensor
test_installation/0 [1]:  File "/hongming/new_torchrec/torchrec/torchrec/__init__.py", line 8, in <module>
test_installation/0 [1]:    import torchrec.distributed  # noqa
test_installation/0 [0]:    from torchrec.distributed.comm_ops import (
test_installation/0 [1]:  File "/hongming/new_torchrec/torchrec/torchrec/distributed/__init__.py", line 36, in <module>
test_installation/0 [0]:  File "/hongming/new_torchrec/torchrec/torchrec/distributed/comm_ops.py", line 27, in <module>
test_installation/0 [0]:    import fbgemm_gpu  # @manual  # noqa
test_installation/0 [0]:  File "/usr/local/lib/python3.7/site-packages/fbgemm_gpu/__init__.py", line 22, in <module>
test_installation/0 [0]:    from . import _fbgemm_gpu_docs
test_installation/0 [1]:    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
test_installation/0 [1]:  File "/hongming/new_torchrec/torchrec/torchrec/distributed/model_parallel.py", line 20, in <module>
test_installation/0 [1]:    from torchrec.distributed.embedding import EmbeddingCollectionSharder
test_installation/0 [1]:  File "/hongming/new_torchrec/torchrec/torchrec/distributed/embedding.py", line 30, in <module>
test_installation/0 [0]:  File "/usr/local/lib/python3.7/site-packages/fbgemm_gpu/_fbgemm_gpu_docs.py", line 12, in <module>
test_installation/0 [0]:    torch.ops.fbgemm.jagged_2d_to_dense,
test_installation/0 [0]:  File "/usr/local/lib/python3.7/site-packages/torch/_ops.py", line 498, in __getattr__
test_installation/0 [0]:    ) from e
test_installation/0 [0]:AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'
test_installation/0 [1]:    from torchrec.distributed.embedding_sharding import (
test_installation/0 [1]:  File "/hongming/new_torchrec/torchrec/torchrec/distributed/embedding_sharding.py", line 15, in <module>
test_installation/0 [1]:    from torchrec.distributed.dist_data import (
test_installation/0 [1]:  File "/hongming/new_torchrec/torchrec/torchrec/distributed/dist_data.py", line 16, in <module>
test_installation/0 [1]:    from torchrec.distributed.comm_ops import (
test_installation/0 [1]:  File "/hongming/new_torchrec/torchrec/torchrec/distributed/comm_ops.py", line 27, in <module>
test_installation/0 [1]:    import fbgemm_gpu  # @manual  # noqa
test_installation/0 [1]:  File "/usr/local/lib/python3.7/site-packages/fbgemm_gpu/__init__.py", line 22, in <module>
test_installation/0 [1]:    from . import _fbgemm_gpu_docs
test_installation/0 [1]:  File "/usr/local/lib/python3.7/site-packages/fbgemm_gpu/_fbgemm_gpu_docs.py", line 12, in <module>
test_installation/0 [1]:    torch.ops.fbgemm.jagged_2d_to_dense,
test_installation/0 [1]:  File "/usr/local/lib/python3.7/site-packages/torch/_ops.py", line 498, in __getattr__
test_installation/0 [1]:    ) from e
test_installation/0 [1]:AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'
test_installation/0 ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1145) of binary: /usr/local/bin/python
test_installation/0 Traceback (most recent call last):
test_installation/0   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
test_installation/0     "__main__", mod_spec)
test_installation/0   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
test_installation/0     exec(code, run_globals)
test_installation/0   File "/usr/local/lib/python3.7/site-packages/torch/distributed/run.py", line 766, in <module>
test_installation/0     main()
test_installation/0   File "/usr/local/lib/python3.7/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
test_installation/0     return f(*args, **kwargs)
test_installation/0   File "/usr/local/lib/python3.7/site-packages/torch/distributed/run.py", line 762, in main
test_installation/0     run(args)
test_installation/0   File "/usr/local/lib/python3.7/site-packages/torch/distributed/run.py", line 756, in run
test_installation/0     )(*cmd_args)
test_installation/0   File "/usr/local/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
test_installation/0     return launch_agent(self._config, self._entrypoint, list(args))
test_installation/0   File "/usr/local/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 248, in launch_agent
test_installation/0     failures=result.failures,
test_installation/0 torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
test_installation/0 ============================================================
test_installation/0 test_installation.py FAILED
test_installation/0 ------------------------------------------------------------
test_installation/0 Failures:
test_installation/0 [1]:
test_installation/0   time      : 2022-09-19_22:44:41
test_installation/0   host      : skyrex
test_installation/0   rank      : 1 (local_rank: 1)
test_installation/0   exitcode  : 1 (pid: 1146)
test_installation/0   error_file: <N/A>
test_installation/0   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
test_installation/0 ------------------------------------------------------------
test_installation/0 Root Cause (first observed failure):
test_installation/0 [0]:
test_installation/0   time      : 2022-09-19_22:44:41
test_installation/0   host      : skyrex
test_installation/0   rank      : 0 (local_rank: 0)
test_installation/0   exitcode  : 1 (pid: 1145)
test_installation/0   error_file: <N/A>
test_installation/0   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
test_installation/0 ============================================================
torchx 2022-09-19 22:44:42 INFO     Job finished: 5
torchx 2022-09-19 22:44:42 ERROR    AppStatus:
  msg: <NONE>
  num_restarts: 0
  roles: []
  state: FAILED (5)
  structured_error_msg: <NONE>
  ui_url: file:///tmp/torchx_32yqu363/torchx/test_installation-jclxjg6pxm1wqc

**Comment by YLGH** [comment]
does your PT verison have cuda enabled? the version looks like:

pytorch 1.13.0.dev20220919 py3.7_cpu_0 pytorch-nightly

**Comment by ZhengHongming888** [comment]
yes. solved according to your suggestion and cuda not enabled. :-)

It's better to change the readme a little with the gpu enable case. The user normally assume with gpu/cpu in default. thanks.

**Comment by YLGH** [comment]
> yes. solved according to your suggestion and cuda not enabled. :-)
> 
> It's better to change the readme a little with the gpu enable case. The user normally assume with gpu/cpu in default. thanks.

Closing this issue since issue is resolved, 

Thanks for your suggestion, sorry that it was confusing. 

Just want to double check:

did you run 
```
conda install pytorch cudatoolkit=11.3 -c pytorch-nightly
```
and this installed the cpu version?

**Comment by ZhengHongming888** [comment]
yes this instruction will give you the cpu version. - conda install pytorch cudatoolkit=11.3 -c pytorch-nightly

Now i am using the official pytorch website instruction as 
conda install pytorch pytorch-cuda=11.6 -c pytorch-nightly -c nvidia 
which will give the gpu version also.

**Comment by YLGH** [comment]
> yes this instruction will give you the cpu version. - conda install pytorch cudatoolkit=11.3 -c pytorch-nightly
> 
> Now i am using the official pytorch website instruction as conda install pytorch pytorch-cuda=11.6 -c pytorch-nightly -c nvidia which will give the gpu version also.

I see - that's definitely not expected, I'll check up on that and update the README, thanks!
