### ISSUE TITLE
Training Hangs for 8 nodes with NCCL backend

### ISSUE THREAD

**Issue by iidsample** [meta-pytorch/torchrec#850]
Setup - 8 Nodes, 1 GPU each (AWS p3.2xlarge)

Script - [facebook research torchrec_dlrm](https://github.com/facebookresearch/dlrm/blob/main/torchrec_dlrm/dlrm_main.py)

Issue - The above script get's stuck on embedding lookup in the forward pass, for the default partitioning generated by Torchrec with NCCL backend. 

Observations - 
We observed the script only gets stuck with NCCL backend and default partitioning. 
If instead we use Gloo backend, or change the partitioning scheme to TableWise the above script works.

**Comment by samiwilf** [comment]
HI @iidsample. I'm not seeing the issue you describe.  Following [this issue template](https://github.com/pytorch/pytorch/blob/master/.github/ISSUE_TEMPLATE.md) would help make sure issues opened on Github are constructive.

**Comment by iidsample** [comment]
### Issue Description 
The [facebook research torchrec_dlrm](https://github.com/facebookresearch/dlrm/blob/main/torchrec_dlrm/dlrm_main.py) script get's stuck on embedding lookup in the forward pass. Based on the default partitioning generated by TorchRec with NCCL backend. 

### Code Example 

We used the example [facebook research torchrec_dlrm](https://github.com/facebookresearch/dlrm/blob/main/torchrec_dlrm/dlrm_main.py)  script provided. The only modification we made was instead of using Terabyte dataset, we used the Criteo Kaggle dataset. 

### System Info
- PyTorch or Caffe2:
- How you installed PyTorch - conda
- Build command you used (if compiling from source): NA
- OS: Ubuntu 18.04
- PyTorch version: 1.12
- Python version: 3.8
- CUDA/cuDNN version: Cuda 11.6
- GPU models and configuration: V100 (1 on each node) and on 8 Nodes

### Additional Information 

We observed the script only gets stuck with NCCL backend and default partitioning. 
If instead we use Gloo backend, or change the partitioning scheme to TableWise the above script works with NCCL as well. 
Further the same code runs fine with 4 machines or 2 machines.

**Comment by iidsample** [comment]
Thanks for looking at the issue. I have added with more details. Looking forward to your feedback

**Comment by samiwilf** [comment]
Just a friendly reminder, always paste inline the exact commands that were run. That is the only way others can know how to run the same commands.  

The Kaggle dataset is currently incompatible with [dlrm_main.py](https://github.com/facebookresearch/dlrm/blob/main/torchrec_dlrm/dlrm_main.py).   For example, [TOTAL_TRAINING_SAMPLES](https://github.com/facebookresearch/dlrm/blob/main/torchrec_dlrm/dlrm_main.py#L25) refers only to the [total number of samples in the Terabyte dataset](https://github.com/pytorch/torchrec/blob/main/torchrec/datasets/criteo.py#L41).

I can try to fix this over the weekend or the next.

**Comment by iidsample** [comment]
Thank you for looking at the issue. Really appreciate the willingness to help with the issue and quick responses. 
We have already fixed the TOTAL_TRAINING_SAMPLES etc., (the script works with gloo backend, or if we don't use the default partitioning and rather use TABLE_WISE or ROW_WISE). This problem *only* happens when using default partitioning with NCCL backend on 8 machines (works for 4 or 2 machines). 

I understand you would need to recreate the issue on your end, I was expecting if you had any idea of things you want us to try. Our guess is for some kind of partitioning topology the embedding fetch using NCCL just gets stuck. 

Thanks again for looking at it.

**Comment by samiwilf** [comment]
One known issue that causes hanging is when a rank tries to iterate through more batches than another rank. The way to stop the hang is to use a [Join context](https://pytorch.org/tutorials/advanced/generic_join.html).  However, something in the mix of TorchRec + Torch.fx + Pytorch's DDP (all of which are used by [dlrm_main.py](https://github.com/facebookresearch/dlrm/blob/main/torchrec_dlrm/dlrm_main.py)) causes Join to not behave properly last I tested a few weeks ago.

**Comment by colin2328** [comment]
@iidsample  is this still not working for you?

**Comment by YLGH** [comment]
Closing for now - feel free to reopen if still blocked by this
