### ISSUE TITLE
Installing torchrec introduces examples package

### ISSUE THREAD

**Issue by cchan-lm** [meta-pytorch/torchrec#853]
Hello, hope you're well! It seems that installing torchrec also installs another `examples` package. To replicate the issue (using Docker to ensure a cleaner environment):

```
docker run -it python:3.9 /bin/bash
```

In the launched terminal from the container, run:

```
pip install torchrec-nightly
```

Running `python` then `import examples` gives an actual module. `examples.__file__` gives `/usr/local/lib/python3.9/site-packages/examples/__init__.py`. Under `/usr/local/lib/python3.9/site-packages/examples` are:
```
__init__.py 
__pycache__ 
datasets
golden_training
ray
retrieval
torcharrow
transfer_learning
```

These look similar to https://github.com/pytorch/torchrec/tree/main/examples, just missing some directories. Is this by design? We have some private repos with their own "examples" directory, and our examples are importable under a certain namespace, while also runnable from our examples directory. When torchrec is installed, we can no longer do `from examples.foo import bar` from within our examples directory. This is pretty surprising given how harmless the name "examples" seems, but this is somehow causing a namespace conflict.

I've also tried `sys.path.insert(0, <path to our examples directory)` which didn't fix our issue.

Any help would be appreciated. Thank you :)

**Comment by YLGH** [comment]
Thanks for reporting this issue, 

this should be fixed after https://github.com/pytorch/torchrec/pull/872

sorry for the delay!

**Comment by cchan-lm** [comment]
No worries, @YLGH! Thank you so much for fixing this!
