### ISSUE TITLE
Using pip install but do not have torchrec.datasets.scripts.nvt folder.

### ISSUE THREAD

**Issue by allenfengjr** [meta-pytorch/torchrec#888]
Hello, I install torchrec by using
`pip install torchrec`

Then I go to the directory but there is no such a folder [nvt at github](https://github.com/pytorch/torchrec/tree/main/torchrec/datasets/scripts/nvt)

I also try `pip install torchrec-nightly`, there is no nvt folder either. I am not sure if I install this package in a right way. If I want to use some bash file in this folder, should I clone this repo directly or should I install in another way? Thank you.

**Comment by YLGH** [comment]
Hey @allenfengjr , thanks for reaching out.

This directory isn't installed as part of the pip package. I'd recommend git pulling the torchrec repo and directly going into that folder. There are also some installation instructions in the README for some nvidia dependencies that that are managed in a Docker container

**Comment by YLGH** [comment]
Closing issue, feel free to re-open if this solution doesn't work
