### ISSUE TITLE
DLRM doesn't work with `dense_in_features = 0`. 

### ISSUE THREAD

**Issue by tiepvupsu** [meta-pytorch/torchrec#984]
I have a dataset where all features are categorical. In theory, DLRM should also work in this special case with output of `Interaction` layer having size `B * (F choose 2)`, i.e. only sparse features interact with each other. 

The code doesn't seem to support this special case. Do you have a plan for that? 

Thank you for this awesome repo.

**Comment by YLGH** [comment]
Hey @tiepvupsu, ah that might be an edge case we hadn't covered, let me see if we can support this

**Comment by YLGH** [comment]
Asked around, and we probably want to keep it this way (since DLRM is something that combined dense + sparse features). We recommend just creating your own sparse layer that just processes the embeddings if you need.
